stdpopsim/__init__.py, stdpopsim/pongo/__init__.py, stdpopsim/pongo/models.py
Adapted the existing template for the Locke etal _Pongo_ model
=> Added Locke etal Pongo IM model

.circleci/config.yml, requirements/development.txt, setup.py, stdpopsim/chromosomes.py, stdpopsim/models.py, tests/test_genetic_maps.py
Some basic tests for genetic map infrastructure and initial CircleCI config.
=> Tests and CI

docs/development.rst
This ended up being quite long, but hopefully takes some of the mystery out of rebasing and squashing.
What do you think @petrelharp, @andrewkern?
=> Add documentation for rebasing.

docs/development.rst
=> flake8 in dev docs

athaliana_example.py, stdpopsim/arabidopsis_thaliana.py, stdpopsim/drosophila_melanogaster.py, stdpopsim/e_coli.py, stdpopsim/genomes.py, stdpopsim/homo_sapiens.py, tests/test_homo_sapiens.py
In addition, I changed out the defined chromosome lengths with those found here : 
`ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/working/20110106_recombination_hotspots/README_hapmapII_GRCh37_map`
=> Added mean recombination rates to chromosome & genome

stdpopsim/__init__.py, stdpopsim/models.py, tests/test_models.py
Closes #39.
Still some work to be done to test all the corner cases, but it basically works I think.
cc @ndukler, @andrewkern.
=> Equality comparison for models.

dmel_example.py, docs/api.rst, docs/development.rst, ecoli_example.py, example.py, stdpopsim/homo_sapiens.py
The examples and the documentation hadn't been updated after #34. There are a copule of other amendments.
=> Minor doc fixes

requirements/development.txt, requirements/rtd.txt, setup.py, stdpopsim/__init__.py, stdpopsim/cache.py, stdpopsim/genetic_maps.py, tests/__init__.py, tests/test_cache.py, tests/test_genetic_maps.py
Closes #38.
WIP. This should resolve the bug, but I need to figure out how to test it (plus test the map downloading code better also).
=> Fix race condition in map cache.

stdpopsim/homo_sapiens.py, tests/test_homo_sapiens.py
Adding the model of American admixture from Browning et al.—see #46. This paper included msprime code in the supplement, which I ported over and modified only for formatting.
=> Adding more human models

docs/development.rst
Added some guidelines for demographic model submission and QC. Look good? @carjed @jeromekelleher
=> Dev docs update for model submission

qc/homo_sapiens_qc.py, tests/test_homo_sapiens.py
Added independent QC implementation of Browning model. Had to do some purely aesthetic tweaks (adding tiny numbers to generation times) to match production model but logic was unchanged.
=> Browning model QC

qc/e_coli_qc.py, tests/test_e_coli.py
Lapierre QC test. Also added start of unit test file for e. coli. Had to remove one of the standard unit tests b/c it required >1 population in the model. @jeromekelleher
=> Lapierre qc

qc/drosophlia_melanogaster_qc.py, tests/test_drosophila_melanogaster.py
Li-Stephans QC implementation. Currently failing equality test due to discrepancy in generation time calculation. @andrewkern @jeromekelleher
=> Li stephans qc

stdpopsim/drosophila_melanogaster.py
@ndukler here is the PR with the fix. once you approve i will merge.
=> fixed a bug with the times in sheehan and song model

stdpopsim/homo_sapiens.py, tests/test_homo_sapiens.py
hey @ndukler here is the single population version. i've already added a stub for the QC tests in `tests/test_homo_sapiens.py`
=> adding a single population Africa model

qc/homo_sapiens_qc.py, tests/test_homo_sapiens.py
QC for TennessenOnePopAfrica model
=> Added TennessenOnePopAfrica QC model

docs/api.rst, docs/parameter_tables/homo_sapiens/BrowningAmerica_params.csv, docs/parameter_tables/homo_sapiens/GutenkunstThreePopOutOfAfrica_params.csv, docs/parameter_tables/homo_sapiens/TennessenOnePopAfrica_params.csv, docs/parameter_tables/homo_sapiens/TennessenTwoPopOutOfAfrica_params.csv, stdpopsim/homo_sapiens.py
First try at documenting human demographic models. Any thoughts?
=> Documentation of human demographic models

docs/api.rst, docs/parameter_tables/drosophila_melanogaster/LiStephanTwoPopulation_params.csv, docs/parameter_tables/drosophila_melanogaster/SheehanSongThreeEpoch_params.csv, stdpopsim/drosophila_melanogaster.py
Documentation for the two d. mel. models. Also added the metadata for the populations.
=> Added D. mel model documentation

qc/homo_sapiens_qc.py, tests/test_homo_sapiens.py
=> QC Ragsdale model and test

docs/api.rst
There's a lot more to document, but I noticed this step was missing.
=> small note on downloading recomb maps

stdpopsim/cli.py, tests/test_cli.py
=> Split out model help on CLI.

appveyor.yml, requirements/conda-minimal.txt, stdpopsim/genetic_maps.py, tests/test_cli.py
=> Initial appveyor configuration.

docs/examples.py, docs/tutorial.rst, stdpopsim/cache.py, stdpopsim/cli.py, stdpopsim/genetic_maps.py, stdpopsim/species.py, tests/test_cli.py, tests/test_genetic_maps.py
Closes #126 
WIP, needs tests.
=> Cache commands

.circleci/config.yml, requirements/development.txt, stdpopsim/cli.py, tests/test_cli.py
~This is based off #131, to avoid duplicating effort. Will be rebased and ready for review once #131 is merged.~
~Also we should get #7 sorted before merging, since there's likely to be some windows quirks with this.~
These are both done now.
=> Stdout output

docs/development.rst
Resolves https://github.com/popgensims/stdpopsim/issues/156
=> update development docs installation section

stdpopsim/catalog/drosophila_melanogaster.py
just cleaning up https://github.com/popgensims/stdpopsim/issues/153
=> add DOI to fly genetic map

docs/api.rst, stdpopsim/genomes.py, stdpopsim/species.py
=> Added Contig to API.

stdpopsim/catalog/arabidopsis_thaliana.py
this when merged will close https://github.com/popgensims/stdpopsim/issues/154
=> added Salome DOI

docs/development.rst
closes https://github.com/popgensims/stdpopsim/issues/141
=> added new people landing docs.

stdpopsim/catalog/homo_sapiens.py
=> Fix browning admixed population

.circleci/config.yml, setup.py
First commit tries to check this in CI to verify.
=> Fix wrong 'attr' package in setup.py

docs/api.rst, docs/catalog.rst
closes #148.
cc @agladstein, could you please have a look at this?
cc @ndukler, there's a placeholder where I'd like to link to your CLI tute once #165 is pulled in.
=> Added intro to the catalog.

docs/introduction.rst
relates to #137.
I added some more text to the Introduction page of the docs to make it a bit friendlier --  feel free to modify or add things.
=> Expanded Introduction of docs.

stdpopsim/catalog/arabidopsis_thaliana.py, tests/test_athaliana.py, tests/test_cli.py
doing some clean up on the existing `Durvasula2017MSMC()` model and added a simpler, two epoch model that was published in 2018 by Christan Huber et al. 
I'll start a QC issue for this now.
=> improving a_thal and added model

stdpopsim/catalog/arabidopsis_thaliana.py, tests/test_athaliana.py, tests/test_cli.py
need to revert and rebase this merge. sorry for the hassle
=> Revert "improving a_thal and added model"

stdpopsim/catalog/arabidopsis_thaliana.py, tests/test_athaliana.py, tests/test_cli.py
okay @ndukler check this out and merge please
=> new PR for huber two epoch

stdpopsim/cli.py, tests/test_cli.py
Adds a `--species-help` option to the CLI which details population defaults
=> WIP --species-help for CLI

qc/pongo_qc.py, stdpopsim/catalog/pongo.py, tests/test_pongo.py
Closes #213.
Added documentation and genome information for the Pongo model. I also included some QC code for it here. Since I also changed the original model (needed to fix the migration rate), it might be worth having an extra set of eyes to avoid me possibly duplicating an error between the original and qc model.
=> Pongo documentation and QC

tests/test_cli.py, tests/test_genetic_maps.py
The test_citations() change might conflict with #214.
=> Add more tests

appveyor.yml, requirements/development.txt, setup.py, stdpopsim/__init__.py, stdpopsim/cli.py, stdpopsim/slim_engine.py
There's plenty more that needs to be done, but its functional already. Try it with:
```
stdpopsim -vv -e slim --slim-no-burnin homsap -c chr22 -l 0.001 -m ooa_3 -o /dev/null 10 10 10
```
The generated SLiM script is intended to be extensible outside of stdpopsim. To obtain the generated SLiM script:
```
stdpopsim -vv -e slim --slim-no-burnin --slim-script-file out.slim homsap -c chr22 -l 0.001 -m ooa_3 -o /dev/null 10 10 10
```
=> Slim backend

.circleci/config.yml, qc/arabidopsis_thaliana_qc.py, qc/drosophlia_melanogaster_qc.py, qc/homo_sapiens_qc.py, qc/pongo_qc.py
Closes #116
Most of the changes here are trivial, but it would be good to have a pair of eyes on this to make sure I haven't introduced any bugs.
=> Lint the QC code and add to pep8 check to CI.

README.md
=> Added Appveyor badge.

docs/_ext/speciescatalog.py, stdpopsim/catalog/arabidopsis_thaliana.py, stdpopsim/catalog/drosophila_melanogaster.py, stdpopsim/catalog/homo_sapiens.py, stdpopsim/catalog/pongo.py, stdpopsim/cli.py, stdpopsim/models.py, tests/test_models.py
Species specific subclasses of stdpopsim.Model have been removed. Addresses #243.
=> Require Model.generation_time, and related cleanups.

.readthedocs.yml
=> Installs the package into the venv with pip.

appveyor.yml, docs/development.rst, requirements/development.txt, requirements/rtd-conda-environment.yml, setup.py, stdpopsim/cli.py, tests/test_cli.py
Closes #161
We lose the nice coloured output for logs, but it's not worth the packaging hassle of dealing with daiquiri.
=> Removed daiquiri requirement.

docs/conf.py
=> Remove msprime mock.

.travis.yml
=> Initial travisCI config.

stdpopsim/cli.py, stdpopsim/species.py
=> Modified wording about default recombination rates.

docs/parameter_tables/Afr_3epoch.csv, stdpopsim/catalog/arabidopsis_thaliana.py, tests/test_athaliana.py
I have added three epoch model from Huber et al. 2018.
=> Added Huber three epoch model

qc/arabidopsis_thaliana_qc.py, qc/drosophlia_melanogaster_qc.py, qc/homo_sapiens_qc.py, qc/pongo_qc.py, stdpopsim/catalog/arabidopsis_thaliana.py, stdpopsim/catalog/drosophila_melanogaster.py, stdpopsim/catalog/homo_sapiens.py, stdpopsim/catalog/pongo.py, stdpopsim/models.py, tests/test_athaliana.py, tests/test_drosophila_melanogaster.py, tests/test_homo_sapiens.py, tests/test_models.py, tests/test_pongo.py
Closes #269.
The Model class is nicer, but the rest is just code churn. There are a couple of things in here that aren't intended to be merged. E.g. the Final metaclass was just to find where the subclasses were hiding. Also, there are two files with dos end of line characters that got converted to unix end of line characters (`qc/arabidopsis_thaliana_qc.py` and `qc/drosophlia_melanogaster_qc.py`), which makes the diffs harder to read.
=> Turn subclasses of stdpopsim.Model into functions.

stdpopsim/engines.py, stdpopsim/species.py, tests/test_engines.py, tests/test_species.py
=> Prevent duplicate engines, species, genetic maps, and models.

docs/_ext/speciescatalog.py, docs/api.rst, docs/catalog.rst, docs/development.rst, qc/arabidopsis_thaliana_qc.py, qc/drosophlia_melanogaster_qc.py, qc/homo_sapiens_qc.py, qc/pongo_qc.py, stdpopsim/catalog/arabidopsis_thaliana.py, stdpopsim/catalog/drosophila_melanogaster.py, stdpopsim/catalog/homo_sapiens.py, stdpopsim/catalog/pongo.py, stdpopsim/cli.py, stdpopsim/engines.py, stdpopsim/models.py, stdpopsim/species.py, tests/test_athaliana.py, tests/test_cli.py, tests/test_drosophila_melanogaster.py, tests/test_homo_sapiens.py, tests/test_models.py, tests/test_species.py
```
find stdpopsim tests qc docs -type f \
-exec sed -i 's/\<Model\>/DemographicModel/g' {} \;
```
Plus line length fixes.
See #303.
=> Rename Model -> DemographicModel.

stdpopsim/catalog/arabidopsis_thaliana.py, tests/test_athaliana.py
=> Updated pop size estimate for aratha and added citation.

docs/api.rst, stdpopsim/models.py, tests/test_models.py
closes https://github.com/popgensims/stdpopsim/issues/298
=> changed name of GenericIM to IsolationWithMigration

stdpopsim/cli.py, tests/test_cli.py
Adds a printout of the simulation details whenever one is run from the CLI
=> Provide information about simulations run from CLI to user

stdpopsim/cli.py, stdpopsim/species.py
closes #216 -- small changes to length multiplier descriptions
=> Changed description of length multiplier.

docs/development.rst
closes https://github.com/popgensims/stdpopsim/issues/122
...i think...
=> updated docs with a new section on Naming conventions

stdpopsim/catalog/arabidopsis_thaliana.py, stdpopsim/catalog/homo_sapiens.py, tests/test_species.py
this PR will close https://github.com/popgensims/stdpopsim/issues/123
=> updated genetic map IDs to meet schema

docs/_ext/speciescatalog.py
Depends on #331 -- will rebase once it's merged.
=> Catalog rendering improvements

docs/_ext/speciescatalog.py, docs/parameter_tables/AraTha/African2Epoch_1H18.csv, docs/parameter_tables/AraTha/African3Epoch_1H18.csv, docs/parameter_tables/AraTha/SouthMiddleAtlas_1D17.csv, docs/parameter_tables/HomSap/AncientEurasia_9K19.csv, docs/parameter_tables/HomSap/Zigzag_1S14.csv
I have added parameters for models:
- Zigzag_1S14
- AncientEurasia_9K19
- SouthMiddleAtlas_1D17
- African2Epoch_1H18
Also I have fixed `speciescatalog.py` to emit warning.
I am not sure for SouthMiddleAtlas_1D17 as I have not found table in the paper, it is based on the code. Also there is no common notation among tables, for example in my tables I used `Time`, but I saw something like `Epoch time` and `ADMIX time` in other places. May be we want to discuss it?
=> Parameter tables for the remaining models and warning when they are missing

stdpopsim/catalog/pongo_pygmaeus.py
=> Fill citation fields for pongo

stdpopsim/genomes.py
=> genetic_map.name should now be genetic_map.id

docs/catalog.rst, docs/parameter_tables/PonPyg/TwoSpecies_2L11.csv, stdpopsim/catalog/pongo_pygmaeus.py
getting the pongo documentation in order so that we can include this when we ship. even without the genetic map I think this is good to go.
=> ponpyg doc hooks

docs/tutorial.rst
Small updates to docs related to #336 and #345.
=> Small fixes to docs (mostly changing --model to --demographic-model).

setup.py
=> Specify version number for attrs module.

stdpopsim/catalog/arabidopsis_thaliana.py, stdpopsim/catalog/drosophila_melanogaster.py, stdpopsim/catalog/homo_sapiens.py, stdpopsim/citations.py, stdpopsim/cli.py, stdpopsim/genomes.py, tests/test_cli.py
closes https://github.com/popsim-consortium/stdpopsim/issues/359
=> adding citation information to genome assembly

setup.py
Slightly reworked version of #356 (@jgallowa07 is still the commit author).
=> added msprime req to setup.py

docs/catalog.rst, stdpopsim/catalog/pongo_pygmaeus.py, tests/test_pongo_pygmaeus.py
=> Remove PonPyg from the catalog temporarily.

.circleci/config.yml, .travis.yml
=> Build SLiM in Circle CI and Travis CI environments.

docs/parameter_tables/HomSap/PapuansOutOfAfrica_10J19.csv, stdpopsim/catalog/homo_sapiens.py
Found by @noscode during QC, #373.
=> Use 3375 generations for Nea/Nea split time in PapuansOutOfAfrica_10J19.

qc/homo_sapiens_qc.py, tests/test_homo_sapiens.py
I have implemented QC model. (Issue [373](https://github.com/popsim-consortium/stdpopsim/issues/373))
However tests that models are equal failed locally. If I comment all admixtures in both model they are equal, but if I add any one admixture, even the same lines in both models then test failed.  May be somebody look at tests and check it?
=> QC for PapuansOutOfAfrica_10J19 model

stdpopsim/catalog/arabidopsis_thaliana.py
Added in more info about the sampling location of the South Middle Atlas population, modifications to the MSMC demography, and more details about the data for the Huber et al model. Tagging @andrewkern for review
=> Updated A Thaliana model documentation

setup.py
=> Require attrs version >= 19.1.0.

docs/api.rst, stdpopsim/cli.py, stdpopsim/engines.py, tests/test_cli.py
Closes #392. Includes related doc changes which closes #361.
=> Support non-hudson msprime simulation models.

stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Add recapitation, and make it the default.

stdpopsim/catalog/homo_sapiens.py
=> Add recombination rate citation for HomSap.

.travis.yml, README.md, appveyor.yml, requirements/conda-minimal.txt, stdpopsim/cli.py, stdpopsim/slim_engine.py, tests/test_cli.py, tests/test_engines.py, tests/test_slim_engine.py
=> Update appveyor config

validation.py
Supports multiprocessing, because some SLiM simulations will be slow. Running the simulations can be easily done on a multicore server and the stats plotted on a workstation. Now it just needs more stats and simulation scenarios.
Output from `./validation.py -j 8 msprime_basic1 slim_basic1` is attached (which took about 40s to run on my laptop).
[msprime_basic1__slim_basic1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4356655/msprime_basic1__slim_basic1.pdf)
=> Validation script.

README.md, README.rst, environment.yml, stdpopsim_example.ipynb
I have the binder linked to popsim-consortium/stdpopsim:master in the README. So, that won't work until this PR is resolved. In the meantime, you can check the binder from my branch by going to
https://mybinder.org/v2/gh/agladstein/stdpopsim/binder?filepath=stdpopsim_example.ipynb
closes https://github.com/popsim-consortium/stdpopsim/issues/201
=> add config for Binder and example notebook

stdpopsim/cli.py, stdpopsim/slim_engine.py, tests/test_slim_engine.py
* Always do recapitation.
* --slim-scaling-factor defaults to 1.
* --slim-burn-in defaults to 10*N generations.
Closes #420, #445, and #449.
=> Change SLiM engine parameters and default behaviour.

validation.py
* Show stats and model docstrings on the figures.
* Rotate "run time" plot to fit model descriptions.
* Add node_arity statistic (disabled). See #444.
* Put allele frequency spectrum on log scale.
* LD calculation can use lots of memory, so look at only the first 1 mb
of the tree sequence.
=> More validation script changes.

docs/api.rst, stdpopsim/slim_engine.py, tests/test_slim_engine.py
See #458.
What do you think @petrelharp? Maybe it should be a classmethod instead?
=> Recapitate and rescale function for advanced SLiM users.

stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Add warning in SLiM engine for odd sample sizes.

stdpopsim/cli.py, stdpopsim/engines.py, stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Pass --dry-run to SLiM engine to permit stronger unit tests.

docs/development.rst
Drafted up some documentation for new users to add demographic models (#162). Happy to change it up, add more or remove stuff, etc. It's also my first time using rst markup, so let me know if the formatting needs some attention as well.
=> Add documentation for new models

.readthedocs.yml, requirements/rtd-conda-environment.yml
Deleted the pip requirements bit since it didn't do anything. Pip installing the package should pull in all the important deps though, so hopefully this will do the trick.
Follow on to #485
=> Move sphinx packages back into conda deps.

docs/installation.rst, docs/introduction.rst
closes https://github.com/popsim-consortium/stdpopsim/issues/454
added links to binder in beginning of intro section and tutorials.
=> added binder links to docs

docs/development.rst
I tried out adding a model for the first time following the docs. Here are some changes that I think would be helpful for a new person.
- I've mostly reorganized
- I also added in some more specific examples of where to find things and what to write
What do you think about the example function?
I've left out details on adding in a unit test until https://github.com/popsim-consortium/stdpopsim/issues/305 is complete.
closes https://github.com/popsim-consortium/stdpopsim/issues/495
=> update adding model docs

.travis.yml
Trying to fix travis CI build, which has been failing for two weeks.
=> Update miniconda url for travis.

.github/ISSUE_TEMPLATE/model-qc-issue-template.md
adding an issue template for Model QC.
Related to https://github.com/popsim-consortium/stdpopsim/issues/506
=> Update issue templates

docs/parameter_tables/HomSap/AshkSub_7G19.csv, stdpopsim/catalog/homo_sapiens.py
This PR is in response to https://github.com/popsim-consortium/stdpopsim/issues/491
Not ready to be merged.
=> add AJ model

qc/arabidopsis_thaliana_qc.py, qc/drosophlia_melanogaster_qc.py, qc/homo_sapiens_qc.py, qc/pongo_abelii_qc.py, stdpopsim/models.py, tests/test_models.py
Applies test for sampling times when doing model QC and updates models to be in compliance.
I'm not sure if setting the default value for the list of populations is working as I don't really have a great grasp of decorators. Could someone look at the `DemographicModels` class?
=> Added function to check sampling time equality

docs/development.rst, qc/__init__.py, stdpopsim/__init__.py, stdpopsim/models.py, stdpopsim/qc/__init__.py, stdpopsim/qc/arabidopsis_thaliana_qc.py, stdpopsim/qc/drosophlia_melanogaster_qc.py, stdpopsim/qc/homo_sapiens_qc.py, stdpopsim/qc/pongo_abelii_qc.py, tests/test_athaliana.py, tests/test_drosophila_melanogaster.py, tests/test_homo_sapiens.py, tests/test_models.py, tests/test_pongo_abelii.py
Model implementers and QC folks no longer need to touch unit tests.
Closes #305.
=> Automate the model testing and QC process.

stdpopsim/catalog/homo_sapiens.py, stdpopsim/qc/homo_sapiens_qc.py
=> Set migrations rate to zero after full population mass migration

stdpopsim/cli.py, tests/test_cli.py
=> Warn when using a non-QCed model.

.circleci/config.yml, stdpopsim/qc/AraTha.py
Sorry circle, I removed this folder and didn't tell you.
=> Don't flake8 non-existant folder.

stdpopsim/catalog/DroMel.py, tests/test_DroMel.py, tests/test_cli.py
=> Remove DroMel chrM.

docs/Makefile, docs/_ext/speciescatalog.py, docs/catalog.rst
title says it all. tried to do a simple reordering in the `catalog.rst` file and found a bug in the `speciescatalog.py` directives we are using
=> reordered catalog docs, found bug in speciescatalog.py, fixed bug

.github/ISSUE_TEMPLATE/species-qc-issue-template.md
=> Species QC issue template

docs/development.rst, stdpopsim/__init__.py
Added documentation for adding a new species. Can someone who had actually done this take a look to make sure the details are correct and laid out in sufficient depth? @agladstein @apragsdale @grahamgower . Addresses #517 as well.
=> Documentation for adding a species to stdpopsim

tests/test_models.py
=> Set population=0 for msprime.SimpleBottleneck.

CHANGELOG.rst, stdpopsim/cli.py, tests/test_CanFam.py, tests/test_cli.py, tests/test_slim_engine.py
=> Change --quiet to a top-level CLI option

stdpopsim/__init__.py, stdpopsim/cli.py, stdpopsim/slim_engine.py, stdpopsim/species.py, stdpopsim/warning_categories.py, tests/test_cli.py, tests/test_slim_engine.py
=> Warn when using --slim-scaling-factor with Q!=1.

stdpopsim/engines.py, stdpopsim/genomes.py
For a project with @cjbattey we were messing with mutation rates to try to get stdpopsim models to lineup with empirical data. This is a whole other can of worms, but in the meanwhile I unfroze the objects referred to in #530
=> unfroze attributes in engine, contig, chromosome

docs/parameter_tables/HomSap/Zigzag_1S14.csv
I noticed a small typo in the zig zag parameter table. Fixed here and cleaned up a bit.
=> Clean up Zigzag model table.

docs/development.rst
Just a little devdocs update to clarify how to format a recombination maps upload
=> Tiny devdocs update

docs/development.rst, update_ensembl_data.py
Added CLI to maintenance script for downloading species data
=> Adds CLI to make downloading species data easier

maintenance/ensembl.py
=> Accept `primary_assembly` as a coordinate system.

docs/development.rst, stdpopsim/models.py, stdpopsim/qc/AraTha.py, stdpopsim/qc/DroMel.py, stdpopsim/qc/HomSap.py, stdpopsim/qc/PonAbe.py, tests/test_models.py
Also reformatted the code with Black.
Closes #304.
=> Convert QC code to use functions instead of classes.

.github/ISSUE_TEMPLATE/species-qc-issue-template.md, docs/development.rst
=> Update species QC template and mention it in the dev docs.

stdpopsim/catalog/HomSap/__init__.py
Arising from species QC #543.
Also closes #208.
=> HomSap: fix spelling in citations.

docs/_ext/speciescatalog.py, docs/api.rst, docs/conf.py, docs/development.rst, stdpopsim/catalog/HomSap/__init__.py, stdpopsim/citations.py, stdpopsim/engines.py, stdpopsim/genetic_maps.py, stdpopsim/genomes.py, stdpopsim/models.py, stdpopsim/slim_engine.py, stdpopsim/species.py
=> Add more docstrings, plus a few cleanups.

docs/introduction.rst
i did a touchup to the intro section of the documentation to try to make it a bit more friendly from the get go
=> trying to make doc intro more appealing

.circleci/config.yml
=> Add virtual env for Python dependencies

.circleci/config.yml, maintenance/__init__.py, maintenance/ensembl.py
=> lint fixes for maintenance folder

.dependabot/config.yaml
just following tskit's lead here it looks like we only need this one file to set up dependabot.
@grahamgower i added you as default reviewer! feel free to not be
closes #627
=> dependabot following tskit's lead

stdpopsim/genomes.py
Partially addresses #530. Not sure if the formatting is correct
=> Add an example of user-specified mutation rates

stdpopsim/engines.py
Removed erroneous reference to `msprime.simulations.Contig`
=> minor doc fix

stdpopsim/catalog/CanFam/__init__.py
Added notes to help with clarifications, but besides that everything looks good!
=> QCed CanFam

README.md
Whoops! (I just copy-pasted this description into a talk, with the extra "simulation"...)
=> removed duplicate "simulation"

.github/workflows/docs.yml
=> Restrict docs action to popsim-consortium repo.

docs/development.rst, stdpopsim/annotations.py, stdpopsim/cache.py, stdpopsim/catalog/AraTha/__init__.py, stdpopsim/catalog/CanFam/__init__.py, stdpopsim/catalog/DroMel/__init__.py, stdpopsim/catalog/HomSap/__init__.py, stdpopsim/catalog/PonAbe/__init__.py, stdpopsim/genetic_maps.py, stdpopsim/utils.py, tests/test_annotations.py, tests/test_cache.py, tests/test_cli.py, tests/test_genetic_maps.py, tests/test_utils.py
* Introduces a CachedData class, which deduplicates functionality
from the GeneticMap and Annotation classes.
* Compares SHA256 checksums for downloaded files.
* Creates utils.untar() and utils.download(), for simpler reuse and testing.
* Replaces urlretrieve so we can set a socket timeout.
Closes #561.
Closes #599.
Closes #583.
~WIP: Still a few things left to do.~
=> Factor out download/cache code and add checksums.

.flake8, .pre-commit-config.yaml, docs/development.rst, requirements/development.txt
Adding pre-commit and black to stdpopsim
=> Adding pre-commit and black

.circleci/config.yml, maintenance/liftOver.py, maintenance/liftOver_catalog.py, maintenance/liftOver_comeron2012.py
#574, plus a fix to make circleci happy.
=> jradrion lift over

.github/workflows/docs.yml
For the `msprime-1.0` branch too.
=> temporarily disable docs build workflow

requirements/CI/requirements.txt, requirements/development.txt, stdpopsim/slim_engine.py
See discussion in #706 . I've also updated the pyslim version.
=> set slim generation on tables

stdpopsim/genetic_maps.py
Also move `file_pattern` into a property, which makes documentation nicer.
=> Document map cache dir

.circleci/config.yml, .github/workflows/tests.yml, setup.py
=> Require Python >= 3.7.

stdpopsim/genetic_maps.py
Small typo I'd seen a few times so thought I'd fix
=> Typo in genetic_maps.py

docs/parameter_tables/HomSap/OutOfAfricaArchaicAdmixture_5R19.csv
Typos in the docs.
@apragsdale, these look right to you?
=> Fix error in parameters table for OutOfAfricaArchaicAdmixture_5R19

.github/workflows/tests.yml, stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Check for minimum SLiM version at runtime.

.circleci/config.yml, .github/workflows/tests.yml, docs/development.rst, pytest.ini, requirements/CI/requirements.txt, requirements/development.txt
Ping @grahamgower. The plan is to make the smallest update we can here, and then transition the code over to use pytest features over time.
One thing I was confused about was all the stuff around running coverage. Is that needed now?
=> Basic changes for pytest

maintenance/ensembl.py, maintenance/main.py, stdpopsim/catalog/AraTha/species.py, stdpopsim/catalog/BosTau/species.py, stdpopsim/catalog/CanFam/species.py, stdpopsim/catalog/DroMel/demographic_models.py, stdpopsim/catalog/DroMel/species.py, stdpopsim/catalog/EscCol/species.py, stdpopsim/catalog/HomSap/species.py, stdpopsim/catalog/PonAbe/species.py, stdpopsim/citations.py, stdpopsim/cli.py, stdpopsim/genomes.py, stdpopsim/species.py, tests/test_HomSap.py, tests/test_annotations.py, tests/test_cli.py, tests/test_genetic_maps.py, tests/test_species.py
A bunch of changes around the process of adding a new species. Hopefully this will make clearer what needs to be done by the original implementers and the follow-up QC.
I'll open a PR for mus_musculus so we can see roughly what it looks like. (now open in #797)
=> Improve tooling around adding species.

docs/_ext/speciescatalog.py
Fixes currently broken docs build.
=> Update catalog code to use new citations layout.

.github/dependabot.yml
=> Change dependabot frequency from daily to weekly.

.github/ISSUE_TEMPLATE/new-species-issue-template.md
A good number of genomes in ensembl are just scaffold-level, with thousands of scaffolds. I don't *think* we want those.
=> ask for chromosome-level assembly

.github/workflows/tests.yml, docs/_ext/speciescatalog.py, requirements/CI/requirements.txt, requirements/development.txt, setup.py, stdpopsim/cli.py, stdpopsim/engines.py, stdpopsim/genetic_maps.py, stdpopsim/models.py, stdpopsim/slim_engine.py, tests/test_slim_engine.py
Fixes #837
I'm assuming that the msprime 1.0 release will not have drastic changes to the API from the beta version, so can get to work fixing some of the changes in msprime that no longer work here.
=> Updating to work with msprime 1.0 beta

stdpopsim/catalog/DroMel/genetic_maps.py, stdpopsim/catalog/DroMel/species.py, stdpopsim/genetic_maps.py, stdpopsim/utils.py, tests/test_genetic_maps.py
Part of the long-overdue species QC (#541).
=> DroMel: add assembly ref, and use recomb rates from Comeron map.

stdpopsim/catalog/DroMel/species.py
=> Add note about where DroMel Ne came from.

stdpopsim/catalog/AedAeg/species.py, tests/test_AedAeg.py
Please double-check this, @manolofperez - I've edited some things (as we discussed).
=> QC for AedAeg (closes #889)

maintenance/ncbi.py
quick patch think I may merge directly
=> added support for mtDNA from NCBI

stdpopsim/catalog/AnoCar/species.py, tests/test_AnoCar.py
okay so we've got some QC conflicts on this one!
it looks like right now generation time and population size don't agree. 
further i was unable to find a recombination rate in the citation listed.
eventually will close #895
=> qc for AnoCar

docs/parameter_tables/AnaPla/MallardBlackDuck_2L19.csv
I forgot to update the parameter table in #883.
=> parameter table fix

docs/selection_example.py, stdpopsim/ext/selection.py, stdpopsim/genomes.py, stdpopsim/slim_engine.py, stdpopsim/utils.py, tests/test_genomes.py, tests/test_slim_engine.py, tests/test_utils.py
Closes #776 and substitutes #877
=> SLiM engine compatibility with msprime-1.0 and support for genomic types and selection

stdpopsim/slim_engine.py
With long genomic element intervals arrays, we currently get:
```
stdpopsim.slim_engine.SLiMException: slim exited with code 1.
ERROR (EidosScript::Parse_PrimaryExpr): unexpected token '.'.
Error on script line 35, character 64:
initializeGenomicElement(0, c(15690025, 15695370, 15695644, ..., 50785172, 50788749, 50788891), c(15690708, 15695484, 15695817, ..., 50785292, 50788797, 50789352));
^
```
In addition, we had three different formats for the output arrays,
so this patch makes all printed arrays use a single function.
=> Don't print "summarized" arrays into the SLiM script.

stdpopsim/cache.py, stdpopsim/catalog/HomSap/annotations.py, stdpopsim/genomes.py, stdpopsim/slim_engine.py, stdpopsim/species.py, tests/__init__.py, tests/test_annotations.py, tests/test_cache.py, tests/test_citations.py, tests/test_cli.py, tests/test_engines.py, tests/test_genetic_maps.py, tests/test_genomes.py, tests/test_maintenance.py, tests/test_masking.py, tests/test_models.py, tests/test_slim_engine.py, tests/test_species.py, tests/test_utils.py
We should do this in the Contig class's __attrs_post_init__, but this requires lots of tests to be updated so I've deferred that for now.
=> Make contigs fully_neutral() by default.

stdpopsim/genomes.py, stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Ensure we're using discrete recombination maps.

.github/workflows/tests.yml, requirements/CI/conda.txt
Just checking if this is still needed...
=> Remove numcodecs from conda deps.

docs/tutorial.rst
importing numpy module to the chunk it is called.
=> importing numpy

stdpopsim/ext/selection.py, stdpopsim/slim_engine.py, tests/test_slim_engine.py
Work in progress, but I thought of pulling it anyway to get some insights from people. 
Adding lognormal to the set of DFE distributions to be run by slim,
Adding scaling factor to the distribution's coefficients (logsd), instead of  multiplying
=> Adding lognormal distribution to DFEs

docs/parameter_tables/HomSap/Africa_1B08.csv, stdpopsim/catalog/HomSap/demographic_models.py
Here's an African demographic model from Boyko et al 2008.
=> Boyko 2008 African demographic model 

docs/tutorial.rst
Added the contig.clear_genomic_mutation_types() in the selection tutorial.
=> Updated selection tutorial

docs/development.rst, stdpopsim/__init__.py, stdpopsim/catalog/HomSap/__init__.py, stdpopsim/catalog/HomSap/dfes.py, stdpopsim/genomes.py, stdpopsim/models.py, stdpopsim/species.py, stdpopsim/utils.py, tests/test_citations.py, tests/test_genomes.py, tests/test_species.py
Adding a DFE class to stdpopsim. The structure is similar to how DemographicModel class was built. 
This is the first attempt, and still not working properly. I need some help to integrate the stuff that is in ext/ to this new class. So we won't necessarily need to do stdpopsim.ext.MutationType(), to specify a given mutation type, for instance.
Maybe @grahamgower can help me with that?
Thanks!
=> Adding DFE class

docs/parameter_tables/HomSap/OutOfAfrica_3G09.csv
Correct the growth rates in parameter tables (https://github.com/popsim-consortium/stdpopsim/blob/main/docs/parameter_tables/HomSap/OutOfAfrica_3G09.csv) according to those used in demographic_models.py
https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/demographic_models.py#L76
https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/demographic_models.py#L77
=> Update OutOfAfrica_3G09.csv: Fix growth rates

stdpopsim/genomes.py, tests/test_engines.py, tests/test_genomes.py, tests/test_slim_engine.py
swapped function name of `clear_features()` 
closes #1074
=> changed `clear_features()` to `clear_DFEs`

docs/development.rst
added a new section of the dev docs to show how to use pytest locally to get code coverage... this is something that i personally haven't known how to do until now and wow it helps!!
=> added section to development on coverage output from pytest

docs/parameter_tables/HomSap/OutOfAfricaExtendedNeandertalAdmixturePulse_3I21.csv
The parameter file before contained parameters from a file I used as a template.
=> parameter file corrected

docs/tutorial.rst, stdpopsim/dfe.py, stdpopsim/genomes.py, tests/test_engines.py, tests/test_genomes.py, tests/test_slim_engine.py
=> swapping out function names

docs/development.rst
After a painful attempt at a rebase over at #1052 with @izabelcavassim I realized that the "what if git rebase goes wrong" instructions could be improved. As written, it gets the diff to `upstream/main`. **However**, if followed literally, this will *undo* all changes made to `upstream/main` since the PR diverged from it! So, the right thing to do (I think) is to first squash the commits, and *then* merge them in. I've rewritten the docs to reflect this (although note that [the git docs](https://git-scm.com/docs/git-merge-base) suggest an alternative workflow, like:
```
fork_point=$(git merge-base --fork-point origin/master topic)
git rebase --onto origin/master $fork_point topic
```
I've left the current recommendation to do a patch and commit because it seems... less magical? But we …
=> git rebase instructions update

stdpopsim/cli.py, tests/test_cli.py, tests/test_slim_engine.py
Starting to draft the CL interface we will want for using annotations with DFEs. following the current convention, i've introduced a `--dfe-annotation` option, that allows the user to give one of the specified annotations and apply it chromosome-wide.
=> setting up dfe annotations for CLI

stdpopsim/cli.py, tests/test_slim_engine.py
Adding --dfe-bed-file as discussed in #1112
=> DFE interval with bed file

docs/tutorial.rst, stdpopsim/cli.py
I have not tested the examples yet, so I don't know if it is working.
=> Adding the selection examples to CLI session of tutorial.rst

tests/test_slim_engine.py
I was working on tracking down #1162, and in the process refactored the DFE CLI tests (so I could isolate where it was happening). I would also like to make this test faster, but I cannot figure out how to do it - [`test_dfe_annotation`](https://github.com/popsim-consortium/stdpopsim/pull/1169/files#diff-b201385bdd9318912fe29722d750c1d4007aa5fa1454b0d8328eb6cba68dcdadR366) needs to simulate a whole chromosome (to use an annotation), and the scaling factor can't be bigger than about 20 (or else we hit the #1162 error). Unless perhaps we can use
```
-i INCLUSION_MASK, --inclusion-mask INCLUSION_MASK
Path to inclusion mask specified in bed format.
```
to speed things up - I haven't tried yet. Does anyone else know, or have good ideas?
=> refactor of DFE CLI tests

.github/workflows/tests.yml
This will close #1177, hopefully.
=> use development SLiM

stdpopsim/slim_engine.py, tests/test_slim_engine.py
The idea of this PR is to add metadata to tree sequences produced by the SLiM engine. I'm focusing on adding information about the DFEs onto the tree sequence and this will have two main uses:
- It will allow us to streamline the way we overlay neutral mutations with `sim_mutations`. The metadata in the ts will encode information about which mutation types SLiM did not simulate and we can simply iterate over those and add them with `sim_mutations`. Importantly, this will make so that the slim mutation type ids are the same as the ones in the original `Contig`, so we won't have to create new mutation types in the "recapitate and mutate" step.
- The metadata is also useful for downstream analyses.  For instance, this will allow people to figure out which intervals have which mutation types …
=> Dfes in ts metadata

.github/workflows/tests.yml
=> Fix test.yml workflow.

stdpopsim/slim_engine.py, tests/test_slim_engine.py
<s>This will close #1164. As a first step to this, I've stored the recombination map in metadata. In the process, I found (I think) and fixed (I think) an off-by-one bug in how we got recombination maps into SLiM. It just meant that the boundaries of recombination map regions were off by one.</s>
*Edit:* all of that was wrong, lol. What this PR does is:
- provides a test that we use in SLiM the recombination map we think
- adjusts how recombination maps are rescaled using `Q`
=> Test recombination map using metadata

stdpopsim/catalog/BosTau/demographic_models.py
0-based counting in time epoch for the BosTau _HolsteinFriesian_1M13 demography to address comment in #579
=> 0-based counting in BosTau _HolsteinFriesian_1M13 #579

docs/development.rst
In this PR are some suggested edits for the "adding a new species" segment of the docs, which seemed to be outdated. I lifted text from the adding species workshop last summer that Andy led (https://github.com/popsim-consortium/workshops/blob/main/adding_species/contributing.ipynb)- these instructions worked for me for adding a new species a couple of weeks ago.
=> Updated docs for adding a new species

docs/development.rst
I thought we could use some more words about how to do all this, and wrote them down here.
=> more docs about species QC

docs/development.rst
Addressing your comment in #1240, @chriscrsmith .
=> a bit more on qc-ing

stdpopsim/catalog/GasAcu/species.py, tests/test_GasAcu.py
**PR for new species:** #1105
If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).
The QC reviewer should start a pull request that fills out the test stubs
with independently obtained values. The reviewer may look at the python code
for rationale provided in comments, but should ignore the actual code
as much as possible - comments in the code should give enough information
that it's obvious how to get the correct value from the provided references.
(In particular, we shouldn't copy-paste the value from the code into the test!)
- This might be genome-wide, or per-chromosome. Both are …
=> added QC for stickleback

stdpopsim/catalog/CaeEle/genetic_maps.py
I've added a new URL for the C. elegans genetic map
=> New URL for the genetic map

stdpopsim/catalog/CanFam/species.py, tests/test_CanFam.py
=> finish QC for CanFam (closes #1242)

stdpopsim/catalog/StrAga/species.py, tests/test_StrAga.py
**PR for new species:** #854
If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).
- This might be genome-wide, or per-chromosome. Both are fine.
- Check there's a comment describing where it came from, and/or how calculated.
- From a publication? Check the value(s) match the publication.
- Calculated somehow? Average over a recombination map? Redo the calculation.
- This might be genome-wide, or per-chromosome. Both are fine.
- Check there's a comment describing where it came from, and/or how calculated.
- From a publication? Check the value(s) match the publication.
- Calculated …
=> QC for StrAga

docs/parameter_tables/PapAnu/SinglePopSMCpp_1W22.csv, stdpopsim/catalog/PapAnu/demographic_models.py, stdpopsim/catalog/PapAnu/species.py
I hadn't added the parameter table for the demographic model in the docs directory in my previous PR. Creating a new PR since that previous PR has already been merged.
=> Added the demographic model docs parameter table for Olive Baboons

stdpopsim/qc/PapAnu.py, stdpopsim/qc/__init__.py
QC for the demographic model for Papio Anubis from [Wall et al. 2022 ](https://academic.oup.com/gbe/article/14/4/evac040/6553910) also see #1216
=> QC for the demographic model for Papio Anubis

docs/catalog.rst
There's a few more in progress, but I thought I'd start on this list!
=> some more QC'ed species

stdpopsim/catalog/AnoGam/species.py, tests/test_AnoGam.py
There's a number of discrepancies that we need to work out yet, @andrewkern...
=> QC for AnoGam - closes #859

stdpopsim/catalog/CaeEle/genetic_maps.py, stdpopsim/catalog/CaeEle/species.py, tests/test_CaeEle.py
Related to issue #1226, PR #904. Also related to genetic map PR #910.
We changed the actual genetic map, so the recombination rate calculations could use a careful review.
=> QC for CaeEle

docs/catalog.rst, stdpopsim/catalog/AnoGam/demographic_models.py, tests/test_AnaPla.py, tests/test_ApiMel.py, tests/test_CaeEle.py, tests/test_DroSec.py, tests/test_GasAcu.py, tests/test_HelAnn.py, tests/test_HelMel.py, tests/test_PapAnu.py, tests/test_StrAga.py
I'll accumulate the last few species in the QC queue here.
=> adding last species to the catalog

stdpopsim/catalog/PanTro/species.py, tests/test_PanTro.py
Edited the species.py and test.py through communication with the original authors
=> QC for chimpanzee

stdpopsim/catalog/DroMel/dfes.py, stdpopsim/dfe.py, tests/test_dfes.py, tests/test_slim_engine.py
Here's the fix I proposed in #1308.
=> Lognormal fix

maintenance/annotation_maint.py, stdpopsim/catalog/AraTha/__init__.py, stdpopsim/catalog/AraTha/annotations.py, stdpopsim/catalog/DroMel/annotations.py, stdpopsim/catalog/HomSap/annotations.py, tests/test_annotations.py
here is a PR including the latest Arabidopsis annotations from Ensembl into the catalog. 
I have already pushed the relevant intervals files to AWS and set the SHA hashes in the `catalog/AraTha/annotations.py` file
this will close #1320
=> Arabidopsis annotations

docs/selection_example.py, docs/tutorial.rst, stdpopsim/ext/selection.py, stdpopsim/genomes.py, stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Remove SLiM checkpointing except for at first DrawMutation

stdpopsim/catalog/PanTro/demographic_models.py
In this pr, I updated the parameters in the BonoboGhost_4K19 model based on Kuhlwilm et al. (2019) Supplementary Table S3 row 7, because @kuhlwilm suggested these parameters fit the data better.
=> Update demographic model BonoboGhost_4K19

stdpopsim/catalog/PapAnu/__init__.py, stdpopsim/catalog/PapAnu/genetic_maps.py
This is in response to https://github.com/popsim-consortium/stdpopsim/pull/1338.
Fixed the error in the genetic map -> Missing sha, incorrect file_pattern, missing import.
=> Fix the error in PapAnu genetic map

.github/mergify.yml
=> Update mergify to match test environment

docs/introduction.rst
=> added bit from CoC to Getting Involved section

docs/conf.py, docs/development.rst, docs/tutorial.rst
Filling out the section for adding a new DFE to the docs.
The QCing process is basically the same as the demographic model, so I wasn't sure if I should repeat that section...
=> docs for adding DFE

.github/workflows/tests.yml, requirements/CI/requirements.txt, requirements/development.txt, stdpopsim/cli.py, stdpopsim/slim_engine.py, tests/test_dfes.py, tests/test_slim_engine.py
=> Convert SLiM allele codes to nucleotides

stdpopsim/slim_engine.py, tests/test_slim_engine.py
=> Have `_SLiMEngine.recap_and_rescale` add DFE metadata to tree sequence

docs/development.rst, stdpopsim/catalog/AraTha/species.py
I'm using a separate PR for this to simplify the diffs. The other PR #1389 can be closed without merging
=> Clean version of new section on adding new species

docs/introduction.rst
=> Add preprint DOI to docs for 0.2.0

CHANGELOG.rst
Summary of feature additions/bugfixes since v0.1.2
=> Changelog for 0.2.0

.pre-commit-config.yaml
Thanks for the alert, @peterdfields - I've checked, and can reproduce the problem, and this fixes it for me.
=> update flake8 link, closes #1433

stdpopsim/catalog/MusMus/species.py, tests/test_MusMus.py
added QC code for MusMus and tweaked the original species.py file. @peterdfields - please check
=> QC implemented for MusMus

stdpopsim/catalog/HomSap/dfes.py
Resolves most of https://github.com/popsim-consortium/stdpopsim/issues/1470 . (Might still want a piecewise constant DFE.)
=> Add Human Lognormal DFE

stdpopsim/catalog/OrySat/demographic_models.py
=> Changed parameters for rice

stdpopsim/qc/OrySat.py, stdpopsim/qc/__init__.py
QC for rice demographic model (BottleneckMigration_3C07) #1459 #1453
=> QC for rice demographic model 

docs/catalog.rst, stdpopsim/qc/OrySat.py, tests/test_models.py
Closes #1523; see that issue for discussion of how this happened (tldr; I merged an old thing without re-running tests).
And: I've looked at the original paper and agree that this is the right value of the mutation rate for that demographic model.
=> fixup of QC for OrySat (Rice) model BottleneckMigration_3C07

maintenance/annotation_maint.py
this patch fixes the weirdness @chriscrsmith found with annotation tar balls.
=> bug fix on annotation script

docs/_ext/speciescatalog.py, docs/conf.py, docs/tutorial.rst
How to actually do this is trivial, but it's worth having a section on it, I think.
Note that I also have adjusted the speciescatalog code so that species sections and subsections are referenceable from within the docs (there was some annoying case weirdness going on).
=> add docs for using DFEs in other species

docs/parameter_tables/AnaPla/MallardBlackDuck_2L19.csv
See https://github.com/popsim-consortium/stdpopsim/issues/1562#issuecomment-2135873819 for context.
=> migration rates fixed to be consistent with the code (issue #1562)

tests/test_genomes.py, tests/test_slim_engine.py
=> test regions outside left, right aren't simulated; closes #1577

docs/_ext/speciescatalog.py
=> Catalog updates

stdpopsim/dfe.py, tests/test_dfes.py
Fixes error popping up in #1599
=> Fix self-reference causing recursion depth error

stdpopsim/cli.py
In line with other recent changes in https://github.com/popsim-consortium/stdpopsim/pull/1593
=> Consistent naming of model mut/rec rate

maintenance/main.py
=> Add ploidy to maintenance stubs

tests/test_slim_engine.py
=> Add test checking how a clipped DFE is handled by SLiM

CHANGELOG.rst, stdpopsim/cli.py, stdpopsim/genomes.py, stdpopsim/species.py, tests/test_cli.py, tests/test_engines.py, tests/test_genomes.py, tests/test_masking.py, tests/test_slim_engine.py, tests/test_species.py, validation.py
=> Deprecate `length_multiplier`

requirements/CI/requirements.txt
I think this is the reason #1612 failed?
=> bumpy numpy & kastore

CHANGELOG.rst
Added PRs #1591 and #558/#600 to CHANGELOG
=> Added PRs 1591 and 558/600 to CHANGELOG

stdpopsim/genomes.py, tests/test_genomes.py, tests/test_species.py
=> informative error message when chrom length > gc length (closes #1405)

maintenance/main.py
patch to maintenance `add_species` routine. new updates to the way we pull data from ensembl broke this routine.
should close #1670
=> patch to add species routine to work with new updates

requirements/CI/requirements.txt
Bundling together #1682, #1684, #1685.
=> bump things

stdpopsim/qc/HomSap.py
QC for the gamma distribution DFE from Kim et al. 2017 (https://doi.org/10.1534/genetics.116.197145). I got the distribution parameters from the gamma model in table S4 for the 1kG EUR dataset and scaled them according to the ancestral population size for the same dataset in table S2 (where I also got the neutral:negative proportions from).
=> Kim 2017 DFE

docs/catalog.rst
ugh forgot to add the species to the docs when merging #1700
=> add rat to catalog doc

tests/test_RatNor.py
will close #1704 
all QC passes. tests added, citations checked, etc
=> QC tests for RatNor------ RATS

CHANGELOG.rst
Here's the updated changelog for the next release, which we were planning would be 0.2.1.
However, @andrewkern is proposing it's 0.3, which seems like a good idea?
=> changelog update

docs/introduction.rst
Added selection pre-print to the docs #1713
=> Added selection pre-print to the docs #1713

CHANGELOG.rst, stdpopsim/catalog/HomSap/dfes.py
Fixes that bug (still need QC).
=> swap pos and neg proportions in PosNeg_R24; closes #1735
