popsim-consortium/stdpopsim

- docs/development.rst
just a quick fix up to the install directions for conda. we needed to specify to the user that they should add the `conda-forge` channel before installing the requirements. I'm also tempted to ask the users to start a new virtual environment in conda for stdpopsim, but perhaps that is overkill.
> quick fix to the docs for conda install

- stdpopsim/homo_sapiens.py
- tests/test_homo_sapiens.py
Partial solution for #14. This adds in the model so that we can remove the other popgensims/demographicModels repository, which is confusing people.
> Quickly port Tennessen et al model.

- dmel_example.py
- stdpopsim/drosophila_melanogaster.py
- tests/test_drosophila_melanogaster.py
I've added the Li and Stephan (2006) model for divergence between African and European D. melanogaster. I've also updated the `dmel_example.py` script run a couple quick tests on each model before trying to do a full chromosome simulation which is much slower due to the large values of 4Nr being simulated.
> added Li and Stephan model, changes to example

- ecoli_example.py
- stdpopsim/e_coli.py
I added a simple constant model for the evolution of Escherichia coli as described in Lapierre et al, MBE, 2016. Lapierre also considers models with gene conversion and selection which is so far not included.
The evolutionary rates have been taken from Table 2 in Lapierre et al.
In the example file, a sample of size 100 is generated.
At the moment this takes less than a minute. This will increase when gene conversion is included.
> added ecoli model from Lapierre et al

- stdpopsim/genetic_maps.py
- stdpopsim/genomes.py
- tests/test_homo_sapiens.py
Simple fix for defining a recombination map across all chromosomes on a species genome.
> flat (0) maps for non-existing chrom maps

- stdpopsim/homo_sapiens.py
- tests/test_homo_sapiens.py
Added the model from [Fu et al., 2013](https://dx.doi.org/10.1038%2Fnature11690). AFAIK this is identical to the Tennessen 2012 model, but I've included the African growth starting @5.1kya and AFR<-->EUR migration parameters.
> add Fu 2013 2-pop model

- stdpopsim/models.py
- tests/test_models.py
Closes #54
Adds another method ``verify_equal`` which tells the user which parts of their models are different.
> Method to raise an exception if models are different.

- stdpopsim/models.py
- tests/test_models.py
Changes definition of all_models so that we only return those defined within stdpopsim. Fixes problem encountered in QC process in #60.
> Refine all_models to only return from within stdpopsim.

- .circleci/config.yml
- requirements/development.txt
- setup.py
- stdpopsim/__main__.py
- stdpopsim/citations.py
- stdpopsim/cli.py
- stdpopsim/genetic_maps.py
- stdpopsim/homo_sapiens.py
- stdpopsim/models.py
- tests/test_cli.py
- tests/test_homo_sapiens.py
@reedacartwright made the point that it would be very helpful for people who have no Python knowledge to be able to run standard simulations. So, I thought it might be a good idea to add a command line interface to stdpopsim which would enable this. Here's a very rough first outline for discussion.
When installed, this would be invoked either via ``stdpopsim`` or ``python3 -m stdpopsim``.
The idea is to use hierarchical subcommands for species/models. So, on the top level we currently have:
```
$ python3 -m stdpopsim --help
usage: __main__.py [-h] [-V] [-v]
{homo-sapiens,arabadopsis-thaliana,e-coli} ...
Run simulations defined by stdpopsim from the command line
positional arguments:
{homo-sapiens,arabadopsis-thaliana,e-coli}
homo-sapiens        Run simulations of human history. …
```
> CLI for running simulations

- stdpopsim/genomes.py
- tests/test_homo_sapiens.py
This is trivial at the moment because we don't have any varying default mutation rates for chromosomes - Still, I think we'll need it at some point and it seems to make sense (It makes my analysis code cleaner because we need genome-wide average for inference). Open to suggestions if anyone thinks otherwise. 
@jeromekelleher, @andrewkern thoughts/review?
> added mean_recombination_rate to genome and respective tests

- qc/__init__.py
- qc/drosophlia_melanogaster_qc.py
- tests/test_drosophila_melanogaster.py
Added QC model for Sheehan-Song. There is a difference with the production model based on t2 which will need to be resolved, probably by making `` (t_1_coal + t_2_coal) * 4 * N_ref``. Note also that there is a discrepancy in the number of generations for the epoch times estimated from ``PSMC`` (which uses 2N) and ``msms`` (which uses 4N) in the paper itself. We went with the generation counts based on the 4N coalescence unit since that is what the deep learning model was actually fit on.
> Sheehan song qc

- dmel_example.py
- stdpopsim/arabidopsis_thaliana.py
- stdpopsim/drosophila_melanogaster.py
- stdpopsim/e_coli.py
- stdpopsim/homo_sapiens.py
- stdpopsim/models.py
- stdpopsim/pongo.py
- tests/test_models.py
this PR attempts to clean up the inconsistency noted [here](https://github.com/popgensims/analysis/issues/32) by adding `generation_time` as a class variable to each of the demographic models. 
the rationale for having `generation_time` under a specific demographic model rather than a property of the species is that each published model might assume a different generation time.
once we merge this, we can update the `Snakefile` on the `analysis` repo to pull this variable directly from the `stdpopsim` module, rather than have it set by the config file.
> added generation times as class variable to demog models

- stdpopsim/homo_sapiens.py
- tests/test_homo_sapiens.py
I've included a basic model that is often used to test demographic inference software (used in the MSMC paper and others), essentially converting an `ms` command to an `msprime` model. Here is the model run through the analysis pipeline with msmc (and with the `steps` modified for plotting to show the full behaviour):
I've used a different `N0` from figure 10 of Schiffel's supplementary material but otherwise the model is unchanged. 
The `ms2msp_nt` is a convenience function for calculating the new `n_t` after a given number of generations given a growth rate and `N0`. 
I'm not sure if this will be stupendously useful to others, but I thought I would include it just in case anyone else wants to benchmark against it.
> Add SchiffelsZigzag demographic model

- generic_example.py
- stdpopsim/__init__.py
- stdpopsim/arabidopsis_thaliana.py
- stdpopsim/drosophila_melanogaster.py
- stdpopsim/e_coli.py
- stdpopsim/generic_models.py
- stdpopsim/homo_sapiens.py
- stdpopsim/pongo.py
- tests/test_homo_sapiens.py
did a bit of work pulling together a `generic_models` bundle that will provide a set of simple models for `stdpopsim` that will be accessible for each of the organisms in a way that should not break the current usage paradigms. that is to say that this set of generic models will be accessible for each organism such that a user can say `homo_sapiens.generic_constant_size()` and get the generic model back. see `generic_example.py` for a usage example. 
the way I have done this involves calling `import` on `generic_models.py` in each of the organism specific files. thus these generic models will also be available at the level of `stdpopsim.generic_model`. Hopefully this is a point of convenience rather than confusion?
additionally I think the generic models are ready to go for the CLI. …
> first commit for generic_models bundle

- qc/arabidopsis_thaliana_qc.py
- tests/test_athaliana.py
I've implemented the QC requested in issue #97 for the Durvasula demographic model of A. Thaliana history. Overall I had no issue with how it was implemented and agreed with the author's decisions, chiefly to mask the first 8 epochs and the last 2, due to the limitations of MSMC as discussed in the referenced article. My only minor point of contention was the decision to round all the values, presumably for readability. I'm not sure if this was completely necessary, and it might be more reproducible to simple copy-paste the MSMC output (which is presented in the chat log in #97) rather than rounding it as both Arun and now myself have done. However, I don't think it's a major issue, and am happy to go forward as is. I've included the QC model in the test suite, and run it with no problem. …
> QC for A. Thaliana Durvasula2017MSMC

- requirements/rtd.txt
Closes #112
Numpy was missing from RTD requirements, causing builds to fail.
> Add numpy to RTD requirements.

- athaliana_example.py
- generic_example.py
- stdpopsim/arabidopsis_thaliana.py
- stdpopsim/drosophila_melanogaster.py
- stdpopsim/e_coli.py
- stdpopsim/generic_models.py
- stdpopsim/models.py
- stdpopsim/pongo.py
- tests/test_athaliana.py
- tests/test_drosophila_melanogaster.py
- tests/test_e_coli.py
- tests/test_models.py
- tests/test_pongo.py
this is the build out of the generic mixin paradigm for all of the non-human genomes that we currently have. be sure to see the new `is_generic` container that I have given to each model. that is only in there to not break the `all_models()` helper function for the test suite.
> further build out of generic models for non-human genomes

- .circleci/config.yml
- stdpopsim/catalog/arabidopsis_thaliana.py
- stdpopsim/catalog/drosophila_melanogaster.py
Builds are currently broken on RTD because the ``make singlehtml`` docs command is failing. This is almost certainly something to do with #120.
Initial commit adds this to CI so at least we see the failure.
> Update CI to build singlehtml docs.

- stdpopsim/cli.py
- tests/test_cli.py
Addressing #130 to add `--help-genetic-maps` option. I tried to closely follow the approach for displaying help with models.
> Add help for genetic maps

- stdpopsim/models.py
- tests/test_models.py
I added a generic IM model (issue #171) to models.py, below the PiecewiseConstantSize model. Possible that this model should live elsewhere?
> Add IM model to models

- docs/api.rst
- stdpopsim/models.py
closes https://github.com/popgensims/stdpopsim/issues/180
closes https://github.com/popgensims/stdpopsim/issues/181
I added what made sense to me. Let me know if there is anything else that you think is necessary for the API docs on those models. 
I'm also not sure if those parameters should actually all be floats, or maybe some are supposed to be ints?
> added docstrings to generic models for API docs

- docs/api.rst
- docs/examples.py
- docs/tutorial.rst
- stdpopsim/__init__.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/models.py
- tests/test_cli.py
- tests/test_engines.py
- tests/test_models.py
- tests/test_pongo.py
This PR is separated into ~~two~~multiple commits. The first adds the ~~`SimulationEngine`~~`Engine` class, retaining API backwards compatibility by making `Model.simulate()` use the default simulation engine. The second commit removes `Model.simulate()` and changes any users of this function so that they first obtain the default simulation engine and use its `simulate()` method. Remaining commits can be squashed in once everyone is happy.
> Implement Engine class and remove Model.simulate().

- stdpopsim/catalog/arabidopsis_thaliana.py
- stdpopsim/catalog/homo_sapiens.py
- stdpopsim/catalog/pongo.py
- stdpopsim/models.py
- tests/test_models.py
Added the ability to set a `sampling_time` attribute for a population that allows for ancient samples. A negative value for this attribute prevents sampling. Updated the models and other functions as necessary. Not sure what tests should be added.
> Added ability to set sample times for populations

- docs/cli_arguments.rst
- docs/conf.py
- docs/index.rst
Closes #197 and #118; uses a very vanilla implementation of sphinx-argparse to show command-line options in the docs. Hopefully this will make also make it easier for us to spot which parts of the CLI help could be improved (see #215).
I have to say, I don't think that the default way that sphinx has organised and rendered these is going to be very clear or accessible for users of `stdpopsim`. I don't even know what 'Positional' and 'Named' arguments are, but these get their own section heading here. All of the simulation-specific commands are hidden inside the 'Subcommands' subsection.
Nevertheless, might be useful to pull this in now so that others can see and comment on it, and we can address these issues in a later pull request.
> Added page showing CLI options using sphinx-argparse.

- stdpopsim/catalog/homo_sapiens.py
- Change the URL to https to avoid redirect
- Delete the URL citation. It's unnecessary (the URL is already recorded in the object if someone wants to find it) and it complicates the Citation class if we have to deal with things that aren't DOIs.
> Small tweaks to HapMap

- stdpopsim/citations.py
- stdpopsim/cli.py
- tests/test_citations.py
- tests/test_cli.py
I've added an option re: issue #157 (and #144) to convert stored DOIs to `bibtex` on the fly through CrossRef's API and write them to a file within `cli.write_citations`. The way I've done it is pretty straightforward, and hopefully easily understandable. It's a very basic implementation right now, and I'm very open to adding in some more interesting extensions.
If the `bibtex` flag is given with a string, then a connection is opened to that path, the stored DOIs are converted, then written. An internet connection *is required* (and this is checked). The connection overwrites itself each time the program is run, so that we don't have giant files unintentionally.  
If the passed citation is not a valid `stdpopsim.Citation` (or is missing the DOI for some reason) then it fails with a custom …
> Write citations to bibtex

- qc/homo_sapiens_qc.py
- stdpopsim/catalog/homo_sapiens.py
- tests/test_homo_sapiens.py
QC model implementation for 9-pop model from Kamm et al (2019). See Issue #167, and note that this model includes ancient samples (#166). There were also some ambiguities (I think) in the published model description, which should be ironed out first as well - see discussion in #167.
> Add qc for Kamm ancient Europe model

- docs/tutorial.rst
Add a tutorial for python API generic model and output a vcf.
I was originally intending to also show how to output a tped file. But, on second thought, doesn't seem that useful to output a tped once you already show how to get a vcf file. PLINK takes vcf and can convert to a tped.
closes https://github.com/popgensims/stdpopsim/issues/173
> Tutorial generic vcf

- docs/introduction.rst
Related to #250. Removes a 'to do' item from introduction of docs.
> Added link to GPLv3 licence in intro.

- stdpopsim/catalog/homo_sapiens.py
- stdpopsim/cli.py
- tests/test_cli.py
A few small things here:
- Fixed a typo in the Tennessen doi
- Writes genetic map citations to bibtex with a test
- Changes name of bibtex option to `bibtex-file` and adds the short `b` option
> Small bibtex changes

- .circleci/config.yml
- docs/conf.py
- docs/development.rst
- docs/tutorial.rst
- requirements/development.txt
- requirements/rtd.txt
Closes #266 
This works locally, but to get it running on RTD I suspect you'll also need to tell it that we are using the `sphinxcontrib.programoutput` extension, and to make `stdpopsim` available to it so that the commands can be compiled remotely.
A few thoughts I had while doing this:
- This will contribute to massive bloat if we use it indiscriminately. I propose that *only help output* should be displayed in this way, and this should be truncated to 20 lines unless abs necessary.
I don't think it's a good idea to be running `stdpopsim` simulations themselves within the program-output blocks -- some of the ones in the existing tutes take some time to run, and I'm not sure what RTD would do with the output files that these commands are supposed to create.
- Presumably, we wanted to do …
> Added sphinxcontrib-programoutput directives in tutorials

- stdpopsim/catalog/e_coli.py
This should be a good reference for the generation time in E coli under lab conditions:
https://dx.doi.org/10.1128/JB.01368-07
However, there is also a good reference for (alternative) generation times in wild populations:
https://dx.doi.org/10.1098%2Frspb.2018.0789
I only included the first one.
> add reference for ecoli generation time fixes #291

- stdpopsim/catalog/drosophila_melanogaster.py
- tests/test_drosophila_melanogaster.py
conveniently the Li and Stephan paper from 2006 publishes Ne estimates from African flies and a generation time (10 gens/yr). I've used that here. I've also included the Schrider et al mutation rate estimate.
> added citations for drosophila attributes

- tests/test_cli.py
This test is bogus, because a model need not use the species citations,
in which case the species citations should absolutely not be written.
But there's no way to determine if a model has imported the species citations
nor not.
See discussion in #316.
> Don't test for the species specific citations in the output.

- stdpopsim/catalog/arabidopsis_thaliana.py
- stdpopsim/catalog/drosophila_melanogaster.py
- stdpopsim/catalog/e_coli.py
- stdpopsim/catalog/homo_sapiens.py
- stdpopsim/citations.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/genomes.py
- tests/test_citations.py
- tests/test_cli.py
Modify citation writing as suggested in #316.
This overloads the addition operator of `Citation` to augment the citation with a reason. An explicit method call might make the code more obvious.
> Add a `Citation.reason` attribute.

- stdpopsim/cli.py
- tests/test_cli.py
i tried to change as little as possible in the cli, so i left function names like `_model_` alone rather than change them to `_demographic_model_`.  can change them if you think we should.
> swapped out -m, --model for -d, --demographic-model in cli

- stdpopsim/catalog/homo_sapiens.py
- tests/test_homo_sapiens.py
This adds citations for generation time (default to 29) and Ne (default to 10**4) in humans.
One thing I'm wondering is where we should add citations for the default mutation rate. I have a recent mutation rate estimate citation included here, and updated the mutation rate, but not sure where the citation should go for it, or how (or if) it is displayed when used in a simulation.
Closes #289
> add citations for homsap attributes

- docs/_ext/speciescatalog.py
- stdpopsim/catalog/arabidopsis_thaliana.py
- stdpopsim/catalog/drosophila_melanogaster.py
- stdpopsim/catalog/homo_sapiens.py
- stdpopsim/cli.py
- stdpopsim/genetic_maps.py
- stdpopsim/utils.py
- tests/test_cli.py
- tests/test_genetic_maps.py
- tests/test_homo_sapiens.py
- tests/test_species.py
- tests/test_utils.py
This should finalise the changes needed in the genetic maps before release. Main changes:
- Tried to add some descriptive documentation to the maps. Users who don't know anything about the maps shouldn't have to read the paper. The long_descriptions attempt to give a summary of how the maps were made. The ``description`` is a shorter one-line description of what the map is.
- Made an attempt to make the IDs more descriptive, plus trying to avoid future name clashes (we could have the male and female maps for deCode later). I'm not sure there's much point in adding a year to the IDs since the combination of descriptive name and assembly is likely to be unique.
> Tidy up genetic map IDs and docs.

- docs/catalog.rst
- stdpopsim/__init__.py
- stdpopsim/catalog/canis_familiaris.py
- tests/test_canis_familiaris.py
TODO: species specific tests and rtd stuff. Anything else missing?
> Add Canis familiaris to species catalog.

- stdpopsim/cli.py
- stdpopsim/species.py
- tests/test_cli.py
Currently affects:
CanFam chrX
DroMel chrX chrY chrM
PonPyg chrX
HomSap chrX chrY
Closes #384.
> Warn when the user runs simulations of non-autosomes.

- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
Fixes population ordering for multipopulation demographies.
I'll rebase onto master once #409 is merged.
> Don't filter populations when simplify()ing.

- stdpopsim/cli.py
- tests/test_cli.py
Closes #428
A little bit of indirection so that we can mock out the correct call. Doesn't seem to be any good way to make sure that we can write arbitrary bytes to stdout when it can be a fileobj or a StringIO.
> Fix error in test redirection of stdout.

- stdpopsim/slim_engine.py
Fixes the first problem found in validation. See #431.
It seems SLiM doesn't use the migration table (yet?), so this just updates node times.
> Adjust ts node times when using SLiM scaling factor.

- stdpopsim/slim_engine.py
- validation.py
Note that only the rate for continuous migrations is multiplied,
whereas the pulse migrations are left unscaled.
Closes #435.
> Multiply migration rates by the scaling factor.

- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
> Use population configurations from oldest epoch for recapition.

- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
Closes #262.
Recombination map positions and rates are stored as arrays in the
SLiM script. As SLiM includes each script in the provenance table,
whole chromosome recombination maps result in very long arrays in
the provenance table. Note also that SLiM versions prior to 3.3
print the entire recombination map when initializeRecombinationRate()
is called.
I'll rebase onto master once #409 is merged.
> Add recombination map support in SLiM engine.

- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
There's something funny going on here when using the truncated
recombination map. Some of the trees still have more than 1 root.
Msprime 1.0 will bring discrete recombination maps, which is a
better way to do recapitation with recombination maps.
Closes #439.
> Just use the mean recombination rate for recapitation.

- requirements/development.txt
- setup.py
This avoids an issue with recapitation, arising due to changes between
msprime-0.7.4 and msprime-current.
https://github.com/tskit-dev/pyslim/issues/71
> Pin pyslim>=0.401.

- docs/development.rst
We didn't have a link to the code of conduct in the developer docs, so I added one.
> link to code of conduct in docs

- stdpopsim/cli.py
- tests/test_canis_familiaris.py
- tests/test_citations.py
- tests/test_cli.py
- tests/test_genetic_maps.py
- tests/test_slim_engine.py
For motivation, see passing tests that are obviously wrong:
https://github.com/popsim-consortium/stdpopsim/pull/475#discussion_r411214337
The problem is that mock.MagicMock() objects ensure all accessed
attributes and methods are successful. This means that unit tests
can do erroneous things, e.g. due to a typo or an API change, but the
test will pass regardless. A simple solution is to provide a `spec`
for the mocked object. In the case of mocking a function, this is
most easily done by passing `autospec=True` to the mock.patch()
or mock.patch.object() call. If a `new` parameter is provided for the
mock, the spec of the new object will be used, so these cases do not
suffer from the problem just described.
Note that autospec=True probably should not be applied to non-function
objects---at …
> Make mock unit tests less brittle, by using autospec.

- docs/tutorial.rst
- stdpopsim/citations.py
- stdpopsim/cli.py
- stdpopsim/slim_engine.py
- tests/test_cli.py
See #473.
This PR makes all terminal output go through the logging module. The `logging` module provides DEBUG, INFO, WARN, ERROR and CRITICAL logging levels. This PR sets the default to show all messages at level INFO and above. DEBUG level is set with the `-v`  CLI parameter, and WARN level is set with `-q`. I've assumed that we'll use exceptions to report errors, so the ERROR and CRITICAL levels are unused.
Terminal output is very similar to before. INFO level messages have no prefix, but DEBUG messages have a simple `DEBUG: ` prefix and WARN messages have a simple `WARNING: ` prefix. The `warnings.warn()` messages are redirected to the default logger.
Example output below.
```
$ stdpopsim HomSap 10 -l 0.01 -o /dev/null -q
```
```
$ stdpopsim HomSap 10 -l 0.01 -c chrX -o /dev/null -q …
```
> Use the logging module for all terminal output.

- stdpopsim/models.py
- tests/test_slim_engine.py
Closes #459.
This is an alternative proposal to #471. The more I think about that PR, the less I like it. All the catalog models have the `generation_time` attribute set, which makes sense in that context, particularly since many of the catalog models use parameters that were inferred using specific generation time assumptions. But the generic models really are "time in units of generations" models, and this PR better reflects that.
> Set generation_time=1 in generic models.

- .readthedocs.yml
- requirements/rtd-conda-environment.yml
Installing a conda environment on the readthdocs host often fails due
to memory exhaustion. But the readthedocs docker images don't include
gsl, which is needed to build msprime when installing with pip.
So this change uses a minimal conda environment, containing only gsl,
and installs the remaining dependencies using pip.
See #468.
> Reduce readthedocs memory footprint.

- stdpopsim/citations.py
- stdpopsim/cli.py
- tests/test_cli.py
Closes #451.
Example output:
```
$ stdpopsim HomSap -o /dev/null -l 0.001 10
Simulation information:
Engine: msprime (0.7.4)
Model id: PiecewiseConstant
Model desciption: Piecewise constant size population model over multiple epochs.
Population: number_samples (sampling_time_generations):
pop0: 10 (0)
Contig Description:
Contig length: 249250.621
Mean recombination rate: 1.1485597641285933e-08
Mean mutation rate: 1.29e-08
Genetic map: None
If you use this simulation in published work, please cite:
[stdpopsim]
Adrion et al., 2019: https://doi.org/10.1101/2019.12.20.885129
[simulation engine]
Kelleher et al., 2016: https://doi.org/10.1371/journal.pcbi.1004842
[genome assembly]
The Genome Sequencing Consortium, 2001: http://dx.doi.org/10.1038/35057062
[mutation rate]
Tian, Browning, and …
```
> Add stdpopsim citation to CLI output.

- qc/homo_sapiens_qc.py
- stdpopsim/catalog/homo_sapiens.py
- tests/test_homo_sapiens.py
Implemented qc version of the 2009 OOA model (to close #492). I'm having issues getting the tests to catch if I made a mistake in implementation, and I think the development docs are out of date (specifically, item 5 under Demographic model review process, perhaps)? Do I need to add anything beyond `qc_model = homo_sapiens_qc.GutenkunstOOA()` to the `TestGutenkunstThreePopOutOfAfrica` class in `test_homo_sapiens.py`?
> Add Gutunkunst OOA QC

- qc/homo_sapiens_qc.py
- stdpopsim/catalog/homo_sapiens.py
- tests/test_homo_sapiens.py
QC model for Schiffels ZigZag. However, I know there are discrepancies between the model in the catalog and the model I've implemented. For example, generation time of 29 vs 30 years (the Schiffels paper used a 30 year generation time, but the model in the catalog has a generation time of 29). But it doesn't appear that the tests have caught that difference. Do I need to do something beyond adding the `qc_model` to the `TestSchiffelsZigzag` class in `test_homo_sapiens.py` to get the comparison tests to work as expected?
> Add zigzag QC

- docs/development.rst
minor edits to model QC docs. added in reference to the Model QC issue template.
closes https://github.com/popsim-consortium/stdpopsim/issues/506
See the Model QC issue template here https://github.com/popsim-consortium/stdpopsim/issues/new/choose
> update model QC docs

- .github/ISSUE_TEMPLATE/bug-report-issue-template.md
- .github/ISSUE_TEMPLATE/feature-request-issue-template.md
Right now the "new issue" page makes it look like the only way to submit an issue is as a QC issue; this will fix that (and give a bit more guidance).
> more issue templates

- stdpopsim/cli.py
- stdpopsim/slim_engine.py
Recent versions of flake8 now complain thusly:
stdpopsim/slim_engine.py:445:13: F999 f-string is missing placeholders
stdpopsim/slim_engine.py:453:13: F999 f-string is missing placeholders
stdpopsim/cli.py:105:23: F999 f-string is missing placeholders
stdpopsim/cli.py:149:21: F999 f-string is missing placeholders
stdpopsim/cli.py:478:21: F999 f-string is missing placeholders
> fix flake8 F999 failures

- stdpopsim/catalog/AraTha.py
- stdpopsim/catalog/EscCol.py
Closes #355.
Theses species were added by @fbaumdicker and @arundurvasula --- would you be kind enough to quickly check that I haven't messed anything up here? Note that for AraTha, the recombination rate was listed as 8.1e-9, but I get `200 / 124000 / 2 / 1e6 = 8.064516129032258e-10`.
> Add missing citations for AraTha and EscCol.

- CHANGELOG.rst
Closes #551
I'll release tomorrow assuming there's no hiccups.
> Changelog for 0.1.2.

- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/slim_engine.py
- tests/test_engines.py
This avoids silently accepting parameters that are misspelt.
See #565.
> Remove **kwargs from engine.simulate().

- stdpopsim/catalog/HomSap/__init__.py
I added genetic maps for _Homo sapiens_ for the 26 populations in Phase 3 of the 1000 Genomes Project from my paper here: https://advances.sciencemag.org/content/5/10/eaaw9206
I also alphabetized the references at the top of `stdpopsim/catalog/HomSap/__init__.py`
I'd be happy to make any additional changes (e.g., are genetic maps unit tested?).
> Add pyrho genetic maps

- stdpopsim/catalog/HomSap/__init__.py
Made minor changes to move from GRCh37 to GRCh38 for the pyrho maps
> pyrho genetic maps for GRCh38

- docs/development.rst
I realized we didn't actually have a link to the code of conduct in the developer docs. Here it is!  I thought about moving the code over to rst, but really it should go somewhere else (it's not specific to stdpopsim for one thing). This is good enough for now, anyhow.
> link to code in developer docs

- docs/selection_example.py
- stdpopsim/__init__.py
- stdpopsim/ext/__init__.py
- stdpopsim/ext/selection.py
- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
Not for merging until at least after the next stdpopsim release. Feel free to ignore this for now. (Unless you're feeling bored, in which case feedback is welcome!)
> WIP: selection for slim engine.

- stdpopsim/ext/selection.py
- stdpopsim/slim_engine.py
Fixes #612.
Not sure how to unittest this. We could just check for `Q` in the initializeMutationType lines of the generated slim script, but this seems fairly fragile.
> Scale the selection coefficient when using a MutationType.

- docs/introduction.rst
The BibTeX citation from the elife website was a tad different than the original bioRxiv citation. I also removed the "." after the authors' middle initial to reflect elife's author list style (see https://elifesciences.org/articles/54967).
> eLife citation

- appveyor.yml
- docs/api.rst
- environment.yml
- maintenance/annotation_maint.py
- requirements/conda-minimal.txt
- requirements/development.txt
- requirements/rtd-conda-environment.yml
- setup.py
- stdpopsim/__init__.py
- stdpopsim/annotations.py
- stdpopsim/catalog/HomSap/__init__.py
- stdpopsim/citations.py
- stdpopsim/species.py
- tests/test_annotations.py
- tests/test_species.py
Hey all-
I've sketched out what i think are the main bits of the infrastructure for dealing with annotation. I've aimed to mirror what we do with genetic maps, although I figure if we do this right we don't have to host the data at all, and instead we can rely on Ensembl (or similar) as I'm doing now. 
The basic idea is that annotations will be downloaded to the cache as a GFF file. Annotations will have citations, ids, etc, just as do genetic_maps. Handling of the actual annotation files is currently done using [pybedtools](https://daler.github.io/pybedtools/), although I haven't build anything in other than a function that gets the annotations from a chromosome (we will need to make this useful with SLiM-- tagging @mufernando to help me).
Currently I only have annotations defined for …
> Annotation WIP

- requirements/rtd-conda-environment.yml
pinned python to version 3.8 in rtd-conda-environment.yml
> pin python 3.8

- .github/workflows/docs.yml
Sorry about all the churn here. Due to the security model this uses, only the workflow yml file on the master branch is executed, even when a pull request happens. So we just have to merge this file in for testing.
> Another fix for the auto docs build.

- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/genomes.py
- stdpopsim/slim_engine.py
- stdpopsim/species.py
- stdpopsim/utils.py
- tests/test_cli.py
- tests/test_masking.py
- tests/test_slim_engine.py
- tests/test_species.py
Inspired by #663, and remembering that we had discussed adding masking features a while back (#104), I thought I'd sketch out a possible way of including a mask for simulating data. It's by no means complete, since I wanted to get feedback about it before putting much more time into it.
Essentially, at the time of defining a `contig`, we can specify the path to a mask file in bed format, where the mask specifies intervals to keep (following the format in the 1000G downloadable strict mask). Then the mask intervals are an attribute of the contig, and after simulating, we use `ts.keep_intervals(contig.mask_intervals)` to keep only the intervals in the tree sequence given by the mask, if given.
E.g.
```
import stdpopsim
species = stdpopsim.get_species("HomSap")
contig = …
```
> Masking simulated data

- .github/workflows/pre-commit.yml
- .github/workflows/tests.yml
- requirements/CI/conda.txt
- requirements/CI/requirements.txt
- requirements/development.txt
This PR is against a new `msprime-1.0` feature branch. In this branch, we can use features of the as-yet-unreleased msprime-1.0. E.g. #644.
> require msprime-1.0

- maintenance/liftOver.py
- maintenance/liftOver_catalog.py
- maintenance/liftOver_comeron2012.py
Here is my **very unpolished** code for doing liftOver between assemblies. I've tested this on humans and flies so far, and it is running without issue for me. The code requires that you have the UCSC liftOver tool installed and that you point to the appropriate chain file using the argument `--chainFile`.  The `--winLen` option controls the interval length over which a weighted average recombination rate is calculated and `--gapThresh` control the length of gaps where recombination rates are set to zero rather than using the chromosome average rate. 
An example command for lifting over the human map would be as follows:
```
python liftOver_assemblies.py 
--species HomSap 
--map HapMapII_GRCh37
--chainFile ./liftOver_chains/hg19ToHg38.over.chain.gz
--winLen 1000
--gapThresh 1000000
```
> added code for lifting over assemblies

- docs/selection_example.py
- stdpopsim/ext/selection.py
- stdpopsim/genomes.py
- stdpopsim/slim_engine.py
- stdpopsim/utils.py
- tests/test_genomes.py
- tests/test_slim_engine.py
- tests/test_utils.py
OK, so the plan is as follows:
One of the arguments to `simulate` is a `Contig` object. This is the class that represents the (contiguous) region to be simulated. It contains information about the mutation rate and the recombination map.
The goal of this PR is to implement a notion of genomic elements (sensu SLiM). These genomic elements are non-overlapping regions of the contig (as determined by start and end positions) in which certain mutation types can occur.
Mutation types can occur at different rates within each genomic element types, and so an important parameter is the proportion of *all* mutations that are going to be each mutation type. By default, a simulation will have one genomic element spanning the whole contig, in which only neutral mutations can occur (and are added via …
> Genomic element

- docs/api.rst
- stdpopsim/genetic_maps.py
- stdpopsim/species.py
The GeneticMap class is definitely not suitable for external code to use and we need to be able to change it going forward. It's not necessary for the documented workflow in the Python API (i.e., using ``species.get_contig()``).
> Remove genetic_map from public API.

- stdpopsim/genetic_maps.py
- tests/test_genetic_maps.py
* If the genetic map is shorter, we extend it to the end of the chromosome
with a zero-rate region. This is the nominal case.
* If the genetic map is longer than the chromsome, we emit a warning and
use the genetic map length. This can occur when there is a mismatch
between the reference coordinates used for the genetic map and the
chromosome. By using the genetic map length, we maintain some
semblance of backwards compatibility.
See #701 and #719.
> Check the genetic map length matches the chromsome length.

- docs/parameter_tables/HomSap/OutOfAfrica_4J17.csv
- stdpopsim/catalog/HomSap/__init__.py
I have attempted to implement the 4 population model presented in Jouganous et al 2017. 
This is my first time contributing to stdpopsim.
> add 4pop HomSap ooa model from Jouganous et al 2017

- stdpopsim/engines.py
- stdpopsim/slim_engine.py
- tests/test_engines.py
As mentioned in #735, I noticed that there's no option to pass further arguments to `msprime.simulate`. I've added `kwargs` to the relevant `simulate` function and added a test that the information is passed through to msprime successfully.
I aslo thought it would be sensible to require the `demographic_model`, `contig`, and `samples` parameters in `simulate` and make all the other arguments keyword-only. When I first started using `stdpopsim` I found the error messages a bit opaque when any of the first three weren't specified and defaulted to `None`. Happy to take this part out of the PR though others don't agree!
> msprime kwargs

- requirements/CI/conda.txt
Reverts popsim-consortium/stdpopsim#742
This seems to have broken a bunch of tests. *sigh*
> Revert "Bump numcodecs from 0.7.2 to 0.7.3 in /requirements/CI"

- .github/workflows/docs.yml
I didn't do this correctly in #759, and found out in the Demes repository which has essentially the same docs action (https://github.com/popsim-consortium/demes-python/issues/204).
> Fix push-to-docs-repo in docs CI action when merging.

- stdpopsim/catalog/HomSap/__init__.py
- stdpopsim/qc/HomSap.py
These are not necessary and make comparing the model with other implementations impossible.
I guess we should consider changelog updates for things like this, but I think it's such an inconsequential change for users we probably don't need to bother.
> Remove time deltas from AmericanAdmixture_4B11

- .github/workflows/tests.yml
- requirements/CI/conda.txt
- requirements/CI/requirements.txt
- requirements/conda-minimal.txt
- requirements/development.txt
- setup.py
Bump slim to version 3.5
Another version of #770, trying to rule out weird cache issues. Conda can't seem to find the msprime packages on Windows (but can for other OSs)
> Minimal changes for msprime 1.0 alpha.

- .github/ISSUE_TEMPLATE/new-species-issue-template.md
This would be a way for someone to compile the relevant information for adding a new species without doing the coding.
> template for requesting addition of a new species

- stdpopsim/catalog/BosTau/__init__.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/genetic_maps.py
- stdpopsim/genomes.py
- stdpopsim/models.py
- stdpopsim/qc/AraTha.py
- stdpopsim/qc/DroMel.py
- stdpopsim/qc/HomSap.py
- stdpopsim/qc/PonAbe.py
- stdpopsim/slim_engine.py
- stdpopsim/species.py
- tests/test_HomSap.py
- tests/test_cli.py
- tests/test_genetic_maps.py
- tests/test_masking.py
- tests/test_models.py
- tests/test_slim_engine.py
- tests/test_species.py
This is an initial pass at converting the codebase to use the msprime 1.0 Demography model, rather than the msprime 0.x model as we currently do.
This will be a messy change, but I think it's something we can do incrementally, which will also move us closer to demes (which will be the future basis for demography).
The first pass here is to just remove the model comparison code we have here, which is using internal msprime APIs, and use msprime's APIs instead. 
My proposal for the transition would be the following:
1. Remove the ``population_configurations``, ``demographic_events`` and ``migration_matrix`` replace with a ``demography`` object. (May get rid of the ``populations`` list as well, since this is redundant, but not in the first pass)
2. Go through all the catalog files and call …
> Transition to msprime 1.0 demography model

- stdpopsim/catalog/DroMel/genetic_maps.py
- stdpopsim/genetic_maps.py
- stdpopsim/utils.py
- tests/test_genetic_maps.py
This lifts the restriction of not allowing directories in the
recombination map tarballs. We add a test for each genetic map,
which is not perfect, but at least completes in a reasonable amount
of time.
Closes #845.
> Fix ComeronCrossoverV2_dm6 and add tests.

- stdpopsim/catalog/DroSec/__init__.py
- stdpopsim/catalog/DroSec/genome_data.py
- stdpopsim/catalog/DroSec/species.py
- tests/test_DroSec.py
Added Drosophila sechellia
closes #855
> added drosophila sechellia

- maintenance/__init__.py
- maintenance/main.py
- maintenance/ncbi.py
- requirements/CI/requirements.txt
- requirements/development.txt
this PR adds `add-species-ncbi` to the maintenance module. it takes as an argument the species name in binomial nomenclature, e.g., "Drosophila simulans". Quotes must be included around the search term 
should work in the meantime to help folks stub stuff out from NCBI
> maintenance extension to stub out from NCBI

- .github/ISSUE_TEMPLATE/species-qc-issue-template.md
Clarifying some things, after discussion with @jeromekelleher. In particular, we're still *not* requiring the QC be totally blind, because the ideal place for documentation of choices is as comments in the code itself.
> qc template update

- stdpopsim/catalog/DroMel/species.py
- stdpopsim/catalog/DroSec/species.py
- Recalculated the average chromosome recombination rate for DroMel based off of the newer liftover map, "ComeronCrossoverV2_dm6". 
- Added a description to explain how this was done and which map was used. 
- Changed the rates in DroSec to reflect these changes.
> Recalculate DroMel average chromosome rate

- maintenance/main.py
- stdpopsim/catalog/AedAeg/species.py
- tests/test_AedAeg.py
- tests/test_AnaPla.py
- tests/test_AnoCar.py
- tests/test_AnoGam.py
- tests/test_BosTau.py
- tests/test_ChlRei.py
- tests/test_DroSec.py
- tests/test_HelMel.py
- tests/test_HomSap.py
- tests/test_StrAga.py
Whoopsie! Fortunately we just started using `approx`.
Can't say I'm a fan of `pytest.approx( )`'s syntax; it's kinda counterintuitive.
> corrected pytest.approx usage (closes #913)

- docs/development.rst
- docs/tutorial.rst
- stdpopsim/catalog/BosTau/demographic_models.py
- stdpopsim/catalog/HomSap/demographic_models.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/models.py
- stdpopsim/qc/HomSap.py
- stdpopsim/slim_engine.py
- stdpopsim/species.py
- tests/test_models.py
See #557.
The issue: implemented demographic models were originally inferred with certain assumptions about mutation rates, generation times, etc, which then are used to calibrate population size and demographic event timings. Since #556, #631, users can specify and simulate with contigs with user-defined mutation rates, so that mutation rates could be set to match what was assumed when a model was first inferred. However, unless a user is very familiar with the literature, they might not be aware that the species' default mutation rate does not match the model they want to use, so that outputs will have measures of diversity that are far too large or too small for that species without realizing it.
One solution, as proposed in #557, is to allow models to have their own mutation rates …
> Allow demographic models to store mutation rates

- docs/parameter_tables/AnaPla/MallardBlackDuck_2L19.csv
- stdpopsim/catalog/AnaPla/__init__.py
- stdpopsim/catalog/AnaPla/demographic_models.py
Here's a demographic model for AnaPla from Lavretsky et al.!
> Mallard demographic model

- docs/parameter_tables/AraTha/African2Epoch_1H18.csv
- docs/parameter_tables/AraTha/African3Epoch_1H18.csv
- docs/parameter_tables/AraTha/SouthMiddleAtlas_1D17.csv
- docs/parameter_tables/BosTau/HolsteinFriesian_1M13.csv
- docs/parameter_tables/DroMel/African3Epoch_1S16.csv
- docs/parameter_tables/DroMel/OutOfAfrica_2L06.csv
- docs/parameter_tables/HomSap/Africa_1T12.csv
- docs/parameter_tables/HomSap/AmericanAdmixture_4B11.csv
- docs/parameter_tables/HomSap/AncientEurasia_9K19.csv
- docs/parameter_tables/HomSap/AshkSub_7G19.csv
- docs/parameter_tables/HomSap/OutOfAfrica_2T12.csv
- docs/parameter_tables/HomSap/OutOfAfrica_3G09.csv
- docs/parameter_tables/HomSap/OutOfAfrica_4J17.csv
- docs/parameter_tables/HomSap/PapuansOutOfAfrica_10J19.csv
- docs/parameter_tables/PonAbe/TwoSpecies_2L11.csv
- stdpopsim/catalog/AnoGam/demographic_models.py
- stdpopsim/catalog/AraTha/demographic_models.py
- stdpopsim/catalog/BosTau/demographic_models.py
- stdpopsim/catalog/DroMel/demographic_models.py
- stdpopsim/catalog/HomSap/demographic_models.py
- stdpopsim/catalog/PonAbe/demographic_models.py
- stdpopsim/models.py
- stdpopsim/qc/AraTha.py
- stdpopsim/qc/DroMel.py
- stdpopsim/qc/HomSap.py
- stdpopsim/qc/PonAbe.py
- tests/test_masking.py
- tests/test_models.py
Add mutation rates to the cataloged demographic models for each species and the parameter tables in docs.
I'm not sure the best way to do this, but each QC model will also need to have mutation rates added. It took me maybe a half hour to follow the doi in each demographic model to the source publication to find the mutation rate used in inference, and *most* were quite obvious. Perhaps someone would be willing to do the same for the QC models and commit to this same PR, so that tests will make sure that mutation rates match between models and their QCs? Any takers? :slightly_smiling_face:
> Catalog mutation rates

- stdpopsim/catalog/ChlRei/species.py
Apologies for the significant delay in following up here (the Growing the Zoo hackathon was a fair bit ago now...) but I've finally been able to both obtain as well as upload the per-chromosome mutation rates for C. reinhardtii to figshare! I've also uploaded both the mutation and recombination rate data to figshare as recommended during the hackathon. 
Technically covers a bit more of #828, though that issue was obviously closed after the merging of #863 back then.
> Add per-chromosome mutation rates to C. reinhardtii and update refs

- docs/parameter_tables/HomSap/Zigzag_1S14.csv
During the fix to the population sizes in the ZigZag model (detailed in #745), the parameter table in the docs weren't updated to reflect that the ancient and recent population sizes should be 5x higher
> fix zigzag parameter table

- docs/selection_example.py
- docs/tutorial.rst
The Kim et al paper simulated under multiple DFEs, some with fixed dominance and some where h is a function of s. Stdpopsim currently only supports fixed h for a given class of selected mutations, but the current parameterization copies the DFE with an h(s) function. Maybe h=0.5 is a better option here, or h could be a an argument of the DFE function. (See popsim-consortium/analysis2#5)
> Fix the dominance coefficient in Kim DFE

- stdpopsim/qc/AnaPla.py
- stdpopsim/qc/__init__.py
The Demographic model implemented for Black duck and Mallard. See Original Model QC Issue [#921](https://github.com/popsim-consortium/stdpopsim/issues/921#issue-858468039)
I reviewed the demographic parameters reported by Lavretsky et al. (2019) (Figure 6), and added the ancestral population size reported to @petrelharp in personal communication. I used these values to implement a demographic model and ran the unit tests. All seems good.
Regarding @petrelharp 's comment about the migration rate, I'm pretty sure that the rate we use in the model is consistent with what Lavretsky and colleagues infer using dadi. The raw dadi estimates (after scaled by N_anc) should be equivalent to the per-generation rate used by the coalescent simulator of msprime. To confirm this with 100%, one may wish …
> Added QC for duck/mallard (AnaPla)

- maintenance/__init__.py
- maintenance/annotation_maint.py
- maintenance/main.py
- requirements/development.txt
- stdpopsim/annotations.py
- stdpopsim/catalog/HomSap/annotations.py
- tests/test_annotations.py
- tests/test_cli.py
- tests/test_maintenance.py
okay here is a PR that fixes up the Annotation class to return non-overlapping intervals using @grahamgower's approach from the Analysis2 repo. 
basics points to this PR:
1. refactored the data type stored to be a numpy array of intervals. the `Annotation.get_chromosome_annotations()` returns this array for use with SLiM
2. the annotation_maint.py script now does the download of the GFF and the interval merge, before tarring stuff up for aws
things to do:
1. i don't know how fragile the `gff.source == "ensembl_havana"` requirement is. should we worry?
2. the way things are written now, species can have more than one annotation. it would be cool to extend this to other choices
3. add a front end for doing the download of genome annotations in the same way that we have for genome assemblies
> Annot fixup

- stdpopsim/catalog/ChlRei/species.py
- tests/test_ChlRei.py
QC for Chlamydomonas reinhardtii #890, #863, #950
@aays Can you explain where you got your generation time from? For now I don't know the source. 
Thanks.
> species QC to ChlRei

- docs/parameter_tables/HomSap/OutOfAfricaExtendedNeandertalAdmixturePulse_3I21.csv
- stdpopsim/catalog/HomSap/demographic_models.py
Additional HomSap demography of an simple OoA with Nenadertal introgression following Iasi et al. 2021 including the extended admixture pulse with a duration of 800 generations.
> Oo a nea ext puls demo

- stdpopsim/catalog/HelMel/species.py
- tests/test_HelMel.py
Hi @percyfal, thanks for adding the _Heliconius melpomene_ to the catalog.
I started doing the QC for this species.
It seems that there is only one parameter that we disagree with. It is the generation time. I saw in [Pardo Diaz et al. 2012](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002752) that they assumed 35 days as the generation time (Material&Methods), but in the table legend, they assumed ten generations per year (almost the same thing). I guess we disagree in how we did the calculations: you approximated as (9.5/100)*365 = 34.675 days/year; I did as (1/10)*365 = 36.5/year. Both are ok as the differences are negligible. What do you think?
> QC for  Heliconius melpomene

- stdpopsim/catalog/HomSap/dfes.py
Adding a DFE for HomSap, from Huber et al., 2017. 
Related to #1096
> Adding Huber et al 2017 DFE for HomSap

- docs/development.rst
I've set up `stdpopsim-docs` so that the `stable/` docs require manual updating (moving the `stable` symlink). I'm sure this could be automated, but it'd be a hard thing to test out and is a super easy update, so I've added this to the dev docs, as well as some other things that I think are part of the release cycle.
> add note on release docs

- README.md
- README.rst
- docs/conf.py
- docs/development.rst
- docs/installation.rst
- docs/introduction.rst
- docs/tutorial.rst
- stdpopsim/cli.py
- stdpopsim/engines.py
We've moved docs over to github pages; this fixes the links to readthedocs.
> fixup docs links

- stdpopsim/annotations.py
- stdpopsim/genomes.py
- stdpopsim/utils.py
- tests/test_utils.py
starting a PR to resolve #1079 
~~one outstanding item from that issue is that I haven't changed the method names of `check_intervals_validity` and `check_intervals_array_shape` to be e.g. `__check_intervals_validity` so that these are private methods~~
> moving annotations to ints, requiring ints in intervals

- stdpopsim/catalog/DroMel/dfes.py
- stdpopsim/catalog/HomSap/dfes.py
- stdpopsim/citations.py
- stdpopsim/cli.py
- tests/test_cli.py
- tests/test_slim_engine.py
So here is the first attempt to include selection (DFE) in the CLI and simulations. 
The way I do so is to allow the user to do the following:
if `-dfe (or --dfe-model)` is equal to **None**:
- then simulations will be done as previously (**without selection**). 
if `-dfe (or --dfe-model)` is equal to a specified model but demography is None:
- then selection is included and a single population constant size model is used for the demographic scenario.
if `-dfe (or --dfe-model)` and `--demographic-model` is defined by our smart user:
- then both parameters are taken into consideration.
There is a specific [place](https://github.com/popsim-consortium/stdpopsim/compare/main...izabelcavassim:DFE-CLI-new?diff=unified#diff-a2f706ab045cd6f2975f074024f6793138850eee3db24a9434a55f79c3c7230aR642), …
> DFE command line interface

- docs/_ext/speciescatalog.py
This resolves the error described in #1123 and now corresponds to the exact same `xticklabels` used by `demesdraw`.
> Pushed fix for error in #1123

- README.md
Sorry to make a whole PR here, I just noticed that at some point the links to the CI badges got broken (and the link to the CircleCI page lead to the project landing page rather than the SVG of the badge so it wouldn't render). Feel free to reject and just fix whenever next updated, just wanted to throw in a quick fix if no one noticed.
Chris
> Fix broken link to status badge

- docs/tutorial.rst
> fix typos in tutorial

- docs/api.rst
- docs/conf.py
- stdpopsim/dfe.py
I noticed some classes were missing from the API, and added a table up top to make it easier to find things. The table looks like this:
> added MutationType and reference tables to the API docs

- stdpopsim/dfe.py
- stdpopsim/slim_engine.py
- tests/test_genomes.py
- tests/test_slim_engine.py
This is a merge of #1151 and #1152 by @mufernando, with minor changes. Closes #1149.
Here's where we're at:
This PR makes it so SLiM does not simulate neutral mutation types, leaving those for msprime.
This is verified, in part, by saving information about mutation types to top-level metadata, when `verbosity=3`, in `ts.metadata['SLiM']['user_metadata']`.
We would *also* like to have stdpopsim store information in top-level metadata (e.g., under `ts.metadata['stdpopsim']`); for instance, which mutation types go with which DFE? @mufernando made a start at this in #1152. But, that's *separate* because (1) we'll be sticking that information in a different slot in metadata (SLiM can only put stuff in `["SLiM"]["user_metadata"]`); (2) we want to put *more* information than what we have easily …
> Do not simulate neutral mutations

- requirements/CI/requirements.txt
Numpy 1.22.0 dropped support for Python 3.7.
Supercedes #1160.
> Bump numpy for Python>=3.8.

- stdpopsim/catalog/HelMel/genome_data.py
- stdpopsim/catalog/HelMel/species.py
- tests/test_HelMel.py
It includes updated chromosome lengths and generation time.
For more information see Issue #880.
> QC for HelMel species

- docs/_ext/speciescatalog.py
- docs/development.rst
I think I've said this in enough places now. (In particular, it now shows up under the "genome properties" table in the Catalog).
> document rate units (closes #1197)

- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
This would add two arguments for the SLiM engine to `.simulate( )`, that writes out to `logfile` a log with columns `generation` and, for each subpopulation, `mean_fitness_pX` and `sd_fitness_pX` (where `X` is the ID of the subpop), the mean and SD of fitness. By default it does this every 1000 generations, but this is controllable with `logfile_interval`. The default is `logfile=None`, which means "don't log". The testing is minimal but sufficient, I think.
> Add a logfile for fitness

- stdpopsim/catalog/DroMel/dfes.py
- stdpopsim/utils.py
This adds the D melanogaster DFE inferred in [Ragsdale et al, 2016](https://doi.org/10.1534/genetics.115.184812) - see Table S1. The inferred DFE assumed negatively selected mutations are drawn from a log-normal with a given proportion, and positively selected mutations all have a fixed selection coefficient with the remaining proportion.
The re-scaling of the log-normal scale parameter should be double-checked, since the mean of the log-normal is given as 2Ne*s. Pretty sure I just need to divide the scale by 2Ne, but this is based on the scipy definition of the log-normal (which should be standard), and I'm not 100% sure if there are differences in the implementation here.
As an aside, since this was fit on top of an inferred single-population demographic history (using the Zambian DPGP3 …
> Add Ragsdale DroMel DFE

- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
I'd forgotten about SLiM's `LogFile.addMeanAndSDColumn( )` function and done the mean and SD of fitness myself. This simplifies the code, but does change the name of the columns - before they were `mean_fitness_pX` and `sd_fitness_pX` for population `X`; but now they are `fitness_pX_mean` and `fitness_pX_sd` - I think the only person this might affect is @izabelcavassim.
> simplify logfile code

- docs/_ext/speciescatalog.py
- stdpopsim/catalog/HomSap/demographic_models.py
This PR addresses a couple of small fixes for the documentation: 
1.  Now all population names in the population table correspond to the `demesdraw` images
2. Small typo in the description of model `OutOfAfricaExtendedNeandertalAdmixturePulse_3I21` in `HomSap`
> doc: catalog now includes pop name (#1128)

- stdpopsim/catalog/BosTau/demographic_models.py
Updated BosTau Holstein demography mut rate #579 to match the supplement https://academic.oup.com/mbe/article/30/9/2209/1002512 value since we use supplement Ne estimates - the supplement mutation rate is meant to be the sequence error anyway, which is what the simulation gives.
@igronau It would be great if you can merge this in. Thanks!
> Updated BosTau Holstein demography mut rate #579

- .pre-commit-config.yaml
- docs/selection_example.py
- requirements/development.txt
- stdpopsim/catalog/AraTha/species.py
- stdpopsim/catalog/HomSap/demographic_models.py
- stdpopsim/catalog/HomSap/species.py
- stdpopsim/engines.py
- stdpopsim/qc/HomSap.py
- stdpopsim/slim_engine.py
- tests/test_AraTha.py
- tests/test_HomSap.py
- tests/test_PonAbe.py
- validation.py
> Update black in pre-commit.

- stdpopsim/catalog/CaeEle/__init__.py
- stdpopsim/catalog/CaeEle/genetic_maps.py
A follow-up PR to #904.
Note: The genetic map has only 3 columns.
> C. elegans genetic map

- stdpopsim/qc/HomSap.py
QC for https://github.com/popsim-consortium/stdpopsim/issues/733 (@grahamgower)
This is my first time doing QC -- so let me know if I'm doing anything wrong.  I was able to (blind) replicate the model.  The only issues I ran into were:
1. The times in generations as currently implemented have all been cast to integers.  e.g., in the notation of Table 4 [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5500150/) T_{CH-JP} is 9kya.  The generation time is 29y so I originally implemented this as `9e3/29` but that caused the tests to fail.  I could get the tests to pass if I changed this to `int(9e3/29)`.  The models are inferred by `moments` which assumes discrete (hence integer) generations so I guess that makes sense, but since they only report to the precision of 9kya, it's not clear …
> QC for OutOfAfrica_4J17

- docs/parameter_tables/HomSap/AncientEurope_4A21.csv
- stdpopsim/catalog/HomSap/demographic_models.py
Added demographic model of Ancient Europe.
> Ancient europe

- docs/parameter_tables/HomSap/OutOfAfricaExtendedNeandertalAdmixturePulse_3I21.csv
- stdpopsim/catalog/HomSap/demographic_models.py
- stdpopsim/qc/HomSap.py
Hi @LeonardoIasi, I read through the paper and supplement and QC'ed the model based on Supplementary Figure 1a and notes in the main text/materials. Great paper by the way, I really enjoyed reading it!
There appear to be some discrepancies between my QC and your implementation:
1. There are two models specified in your supplementary figure 1, I think the description of the model should make clear that stdpopsim only implements the simpler model (the one in Supp. Figure 1a).
2. The only generation time I see specified in the paper or supplement is 29 years (in the discussion) vs. 25 years in your parameter file. Additionally, the model implementation divides this by 1000 (`25 / 1000`) so that years can be specified in kya. I would suggest keeping everything in years so that …
> qc OutOfAfricaExtendedNeandertalAdmixturePulse_3I21

- stdpopsim/catalog/ApiMel/species.py
- tests/test_ApiMel.py
> * [x]  Recombination rate.
>   
>   * This might be genome-wide, or per-chromosome. Both are fine.
>   * Check there's a comment describing where it came from, and/or how calculated.
>   * From a publication? Check the value(s) match the publication.
>   * Calculated somehow? Average over a recombination map? Redo the calculation.
> * [x]  Mutation rate.
>   
>   * This might be genome-wide, or per-chromosome. Both are fine.
>   * Check there's a comment describing where it came from, and/or how calculated.
>   * From a publication? Check the value(s) match the publication.
>   * Calculated somehow? Redo the calculation.
> * [x]  Recombination map (if present).
>   
>   * Does it match the assembly? Liftover is fine, if clearly stated.
>   * Is the description/long_description a good …
> QC for honeybee

- docs/parameter_tables/BosTau/HolsteinFriesian_1M13.csv
- stdpopsim/qc/BosTau.py
- stdpopsim/qc/__init__.py
[  including updated mutation rate in doc for BosTau demographic model
(HolsteinFriesian_1M13.csv) to fit the one used in model   ]
> QC for HolsteinFriesian_1M13 demographic model for BosTau

- stdpopsim/catalog/HomSap/demographic_models.py
- stdpopsim/qc/HomSap.py
@awohns and I QC'ed the AncientEurope_4A21.
> QC for AncientEurope_4A21

- docs/parameter_tables/PonAbe/TwoSpecies_2L11.csv
I found that the migration rates are missed in the documentation for the demographic model of Pongo abelii. The description of the model is correct. I checked the paper and model code in `stdpopsim` - both includes migrations. Thus, I just add descriptions in the docs table.
> Add missed migration parameters for PonAbe model in documentation

- stdpopsim/catalog/PanTro/species.py
- tests/test_PanTro.py
My bad - I merged #1291 over-hastily, forgetting to remove the pytest.mark.skip's. This fixes that and makes the generation time agree, as discussed in #1220.
> Fixup of PanTro QC (closes #1220)

- stdpopsim/catalog/HomSap/genetic_maps.py
This is to complete https://github.com/popsim-consortium/stdpopsim/issues/543
The lifted over genetic maps have been added to AWS and the corresponding details have been updated in HomSap/genetic_maps.py
New map options HapMapII_GRCh38 and DeCodeSexAveraged_GRCh38 have been created in addition to the original HapMapII_GRCh37 and DeCodeSexAveraged_GRCh36.
> Added new recombination maps for HapMap and deCode lifted over to GRCh38

- stdpopsim/catalog/EscCol/species.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/genomes.py
- stdpopsim/species.py
- tests/test_EscCol.py
- tests/test_cli.py
- tests/test_genomes.py
- tests/test_species.py
- validation.py
This adds a mean gene conversion rate and gene conversion tract length to the chromosome class, as discussed in #846 .
In addition, the corresponding gene conversion parameters for EscCol are added which closes #847 .
It should now be possible to define the gene conversion rates and tract lengths for other species.
So far I did not notice any complications with the existing species and models.
However, the ploidy of the msprime engine is currently hardcoded and set to 2, which doubles the population size of EscCol.
But as integrating the ploidy into stdpopsim is much more entangled with the other species and demographic models, I did not touch the ploidy in this PR. I will open another issue for the ploidy generalization.
> adding gene conversion support

- docs/tutorial.rst
- stdpopsim/ext/selection.py
- stdpopsim/genomes.py
- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
Following the rationale/outline [here](https://github.com/popsim-consortium/stdpopsim/issues/1082#issuecomment-966730838):
- Replace `mutation_type_id` with string `mutation_id` in various extended events (`ext.DrawMutation`, etc)
- Add `Contig.add_single_site_mutation_type` to create a named, interval-less DFE representing a point mutation
- Modify `slim_makescript` to match `mutation_id` to `DFE.id`; check for uniqueness of name, lack of interval, etc when parsing extended events
- Update tests accordingly
> Use string `mutation_id` in place of integer `mutation_type_id` in extended events 

- requirements/CI/conda.txt
- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
With these changes, tests now pass using the new version of SLiM on my computer at least. Mostly this just required changing "generation" to "tick"; there was only one thing that was hard to track down.
> port to slim v4

- docs/catalog.rst
I noticed that PanTro has been reviewed (see `tests/test_PanTro.py`), so it can be added to the catalogue (i.e., made visible in the docs). Note that it's demographic model hasn't yet been (waiting on #1227), but that's OK.
> add PanTro to the catalogue

- .github/workflows/tests.yml
Let's see if this works. However, 18 is still supported [until next April](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes) so maybe I'm jumping the gun here.
> update ubuntu in tests (closes #1353)

- .github/workflows/tests.yml
- docs/tutorial.rst
- stdpopsim/cli.py
- stdpopsim/genetic_maps.py
- stdpopsim/genomes.py
- stdpopsim/species.py
- stdpopsim/utils.py
- stdpopsim/warning_categories.py
- tests/test_genomes.py
- tests/test_masking.py
- tests/test_slim_engine.py
- tests/test_species.py
Mostly addresses #1346, #670, #401 (and supersedes #402) by adding a way to get a contig from an arbitrary interval of a named chromosome.
Thanks to `msprime.RateMap.slice` this was pretty straightforward, except for the handling of coordinates when DFEs are added. I opted to use the same coordinate system as the chromosome from which the contig is extracted, so for example the following adds a DFE in the middle of the contig:
```python
species = stdpopsim.get_species("HomSap")
contig = species.get_contig(chromosome="chr1", left=1e6, right=1.1e6)
contig.add_dfe(intervals=[[1.05e6, 1.06e6]], dfe=...)
```
IMO this is cleaner than requiring the user to manually shift the DFE coordinates (and is less confusing with DFE bed files, annotations, etc).
Previously, if an added DFE had an interval …
> Add API to get contig from region of named chromosome

- .github/workflows/tests.yml
- docs/selection_example.py
- docs/tutorial.rst
- stdpopsim/ext/selection.py
- stdpopsim/genomes.py
- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
- Fixes #1329 and #1082.
- Fixes a bug in the SLiM engine at https://github.com/popsim-consortium/stdpopsim/blob/ec4fedd9859dc23b7b12013d69172d851a5d43d2/stdpopsim/slim_engine.py#L217 that caused fitness calculations to be disabled for one generation after a restore. This probably had very little impact on simulation correctness, but did reduce efficiency of the rejection sampler.
- Fixes a bug where fitness logging would be disabled if the logging interval was set to every generation.
- Removes `selection_coeff` and `dominance_coeff` as arguments from `Contig.add_single_site`, as these are now specified in `ext.selective_sweep`. For the lower-level API this means that these parameters have to be set by a `ChangeMutationFitness` event.
- Fixes #1336.
- Fixes #1337 and #608.
- "Fixes" …
> Add API for selective sweeps

- docs/_ext/speciescatalog.py
- docs/api.rst
- stdpopsim/catalog/DroMel/species.py
- stdpopsim/catalog/EscCol/species.py
- stdpopsim/catalog/StrAga/species.py
- stdpopsim/citations.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/genomes.py
- stdpopsim/species.py
- tests/test_AnaPla.py
- tests/test_DroMel.py
- tests/test_EscCol.py
- tests/test_HomSap.py
- tests/test_StrAga.py
- tests/test_cli.py
- tests/test_engines.py
- tests/test_genomes.py
- tests/test_species.py
- validation.py
Closes #1332; see there for discussion. Summary:
- `bacterial_recombination` is a property of a Genome and of a Contig; if this is True then recombination is all GC, so
* `gene_conversion_fraction` must *not* be set
* `gene_conversion_length` *must* be set
* the recombination rate is converted at simulate( )-time to a gene conversion rate
- otherwise (ie for 'crossover' recombination), "recombination rate" is crossover rate, so:
* if total rate of crossover + gene conversion is `total_rate` then `recomb_rate = total_rate * (1 - gc_frac)`
* so for msprime, we set gene conversion rate to `gc_frac * total_rate = recomb_rate * gc_frac / (1 - gc_frac)`, where `recomb_rate` is the *mean* rate for the recombination map (since this must be constant)
* and for SLiM we set the recombination rate …
> revision to gene conversion API

- docs/development.rst
- stdpopsim/slim_engine.py
- stdpopsim/utils.py
- tests/test_slim_engine.py
Fixes #1406.
Should probably add a test for equivalence between msprime and SLiM engines when `contig.ploidy != 2`.
> Rescale haploid population size in SLiM engine

- requirements/CI/requirements.txt
codecov is [back](https://about.codecov.io/blog/message-regarding-the-pypi-package/) on pypi -- though I'm not clear if it even needs to be in requirements.txt at all.
> Bump codecov to 2.1.13

- stdpopsim/dfe.py
- tests/test_dfes.py
This just adds the Uniform DFE class. In #1481 it was raised whether we also need "log uniform", that we'd do with something like
```
exp(runif(1, logmin, logmax))
```
... but we have no use cases for it, I think, so I'm not adding that.
> add uniform DFE (closes #1481)

- .github/workflows/tests.yml
- CHANGELOG.rst
- requirements/CI/requirements.txt
- stdpopsim/dfe.py
- stdpopsim/slim_engine.py
- tests/test_dfes.py
- tests/test_slim_engine.py
Here's an implementation of the "discretized h-s relationship" discussed at #1488. There *is* a small backwards incompatibility here; that is that the "slim_mutation_id" entry we record in the top-level metadata is now a list instead of a single value. I think this is okay because we'll be doing a new release (and so can mention this), and our storing of things in metadata is not documented yet anyhow.
Note in particular that with this, we will be decoupling the "mutation type" of SLiM from the "mutation type" of stdpopsim (ie a single stdpopsim mutation type may produce mutations of many SLiM mutation types). This is why it was perhaps a lack of foresight to model the DFE machinery after SLiM's mechanics rather than motivating biology. 
To understand what's going on here, read "10.6 …
> h-s relationship (closes #1488)

- .github/workflows/tests.yml
- stdpopsim/catalog/HomSap/dfes.py
For #1494 .
Adding human DFE from Kyriazis et al. Will need to finish this once the h-s relationship PR (#1498) is in, for now this is only half finished but the values are in place at least.
> adding "generic" human DFE

- .github/workflows/tests.yml
- docs/parameter_tables/PhoSin/Vaquita2Epoch_1R22.csv
- stdpopsim/catalog/PhoSin/__init__.py
- stdpopsim/catalog/PhoSin/demographic_models.py
I implemented the 2-epoch demographic model from Robinson et al. (2022), which is what we plan on using for the simulations in the selection paper (for DFE inference). See #1508
> Implemented 2-epoch demographic model for Vaquita

- .github/workflows/tests.yml
> Fix find-conda step in tests.yml

- stdpopsim/qc/MusMus.py
- stdpopsim/qc/__init__.py
After a thorough manual inspection of the code, I now implemented the QC for the three demographic models. See [#1528](https://github.com/popsim-consortium/stdpopsim/issues/1528).
> Implemented QC for three mouse demographic models

- stdpopsim/catalog/PhoSin/__init__.py
- stdpopsim/catalog/PhoSin/annotations.py
So far this includes only the annotations.py file. Waiting on #1514 to add PhoSin to catalog.
@andrewkern, how do we upload files to AWS? Currently the interval files are sitting here:
```
http://sesame.uoregon.edu/~chriscs/StdPopSim/Phocoena_sinus.mPhoSin1.pri.110_exons.tar.gz
http://sesame.uoregon.edu/~chriscs/StdPopSim/Phocoena_sinus.mPhoSin1.pri.110_CDS.tar.gz
```
> PhoSin annotations

- stdpopsim/catalog/AraTha/annotations.py
- stdpopsim/catalog/DroMel/annotations.py
- stdpopsim/catalog/HomSap/annotations.py
- stdpopsim/catalog/PhoSin/annotations.py
The annotations checksums changed in the vaquita annotation PR #1520 
```
$ python -m pytest
========================================================= test session starts =========================================================
platform linux -- Python 3.8.17, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/chriscs/StdPopSim/Temp1/stdpopsim
configfile: setup.cfg
testpaths: tests
plugins: xdist-3.3.1, cov-4.1.0
4 workers [2416 items]  
............................................................................................................................... [  5%]
............................................................................................................................... [ 10%]
................................................................................................ …
```
> new checksums

- stdpopsim/qc/PhoSin.py
- stdpopsim/qc/__init__.py
- tests/test_PhoSin.py
This includes QC for the vaquita species (#1525) and 2 epoch demographic model (#1530). I'm currently failing a strange test related to the parameter table for an AnaPla demographic model so hoping to get some help to figure out why. 
Its been a while since I've made any contributions to stdpopsim so apologies if I have messed anything up in the workflow...
> Vaquita QC

- stdpopsim/catalog/PhoSin/__init__.py
- stdpopsim/catalog/PhoSin/dfes.py
implemented model from Robinson et al. (2022), including documentation and the h-s relationship
> Implementation for Vaquita DFE

- stdpopsim/cli.py
I looked at this a fair bit, and tried to figure out why the [`LogRecord` object](https://docs.python.org/3/library/logging.html#logrecord-objects) that previously had non-empty `args` now has empty logs, and also how to have a unit test for this, but didn't manage to on both counts.
On the other hand, I don't actually think this code was actually doing anything:
```
$ python3 -m stdpopsim -e slim --slim-scaling-factor 10 HomSap -c chr22 --left 10000000 --right 10010000 -o foo1.ts -d Africa_1T12 AFR:100
Simulation information:
Engine: slim (4.1)
Model id: Africa_1T12
Model description: African population
Population: number_samples (sampling_time_generations):
AFR: 100 (0)
Contig Description:
Contig origin: chr22:10000000-10010000
Contig length: 10000.0
Contig ploidy: 2
Mean recombination …
```
> remove custom log message editing (closes #1545)

- CHANGELOG.rst
- stdpopsim/cli.py
- stdpopsim/genomes.py
- stdpopsim/slim_engine.py
- stdpopsim/species.py
- stdpopsim/utils.py
- tests/test_genomes.py
- tests/test_slim_engine.py
As discussed in #1404.
Closes #1404.
> Remove shifting of coordinates

- requirements/CI/requirements.txt
- validation.py
All the pairs run successfully and generate output now. Might be worth a spot check or two by someone else that a. knows what the previous output looked like b. has a different version of libraries installed (I'm using the analysis2 conda env).
Closes #786
> various fixes after msprime api updates

- .github/ISSUE_TEMPLATE/species-qc-issue-template.md
- .pre-commit-config.yaml
- CHANGELOG.rst
- README.md
- docs/api.rst
- docs/catalog.rst
- docs/development.rst
- docs/introduction.rst
- docs/parameter_tables/BosTau/HolsteinFriesian_1M13.csv
- docs/tutorial.rst
- stdpopsim/catalog/BosTau/demographic_models.py
- stdpopsim/catalog/BosTau/species.py
- stdpopsim/citations.py
- stdpopsim/cli.py
- stdpopsim/engines.py
- stdpopsim/genetic_maps.py
- stdpopsim/genomes.py
- stdpopsim/models.py
- stdpopsim/qc/BosTau.py
- stdpopsim/slim_engine.py
- stdpopsim/species.py
- stdpopsim_example.ipynb
- tests/test_cli.py
- tests/test_dfes.py
- tests/test_genetic_maps.py
- tests/test_genomes.py
- tests/test_models.py
- tests/test_slim_engine.py
- tests/test_species.py
Here is implementation for https://github.com/popsim-consortium/stdpopsim/issues/1225.
I get almost all tests passing on my end:
* had to change `np.NINF` to `-np.inf` (new numpy)
* `TestRegisterQCDFE.test_register_qc` seems to have deep recursion, but that is not due to my changes (I think)
```
============================================================================== FAILURES ==============================================================================
_________________________________________________________________ TestRegisterQCDFE.test_register_qc _________________________________________________________________
[gw2] darwin -- Python 3.12.7 /opt/homebrew/Caskroom/miniconda/base/envs/popsim/bin/python
self = <tests.test_dfes.TestRegisterQCDFE object at 0x1094932f0>
def …
```
> Demographic model recombination rate

- docs/parameter_tables/BosTau/Angus_1B16.csv
- docs/parameter_tables/BosTau/Fleckvieh_1B16.csv
- docs/parameter_tables/BosTau/HolsteinFriesian_1B16.csv
- docs/parameter_tables/BosTau/Jersey_1B16.csv
- stdpopsim/catalog/BosTau/demographic_models.py
I have added four BosTau demographies from Boitard et al. (2016) https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005877 to complement the one from MacLeod et al. (2013) https://doi.org/10.1093/molbev/mst125
> Added BosTau demographies from Boitard et al. (2016)

- stdpopsim/engines.py
- stdpopsim/slim_engine.py
- tests/test_models.py
As discussed in #745, the intention was to remove this warning after a while. It's been a while!
> remove zigzag warning

- docs/tutorial.rst
In perusing #1584 I realized we hadn't written down this thing about the coordinate system being fixed even when we simulate a chunk. Now it's written down - hopefully without assuming the reader understands tskit too much?
> docs on missing data and coordinate systems, closes #1584

- CHANGELOG.rst
- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
We did not have robust checks for SLiM's population size trajectories. That's a good bit better now (although we could probably think of more complicated demographic scenarios to check). Issues I uncovered:
- we were effectively computing population sizes during growth phases by doing
`round(round(exp(-r*t)*final_size) * exp(r*t))`; since `round` and `exp` don't commute,
this is not ideal; so I removed the inner `round` (storing initial sizes as floats not ints)
- since population sizes are set in `late()` but these don't take effect until the next time step, the final population sizes was not what you'd think (it was more like what it would have been in the previous time step); I've changed the growth rate used by SLiM slightly so that they agree. A better fix might be to do all that …
> SLiM population size trajectory adjustment

- docs/tutorial.rst
I always forget what the syntax is here! I think others might find it useful.
> Illustrate use of both dtwf and hudson msprime models

- .github/ISSUE_TEMPLATE/dfe-qc-issue-template.md
- docs/development.rst
This is not that detailed, but perhaps detailed enough?
> finalize DFE development docs; closes #1085

- tests/test_slim_engine.py
There's no bug in #1496, but this tests confirms that.
> check mutations are added at the correct time; closes #1496

- tests/test_slim_engine.py
I'm making these not stochastic; the argument here is that if there's a failure in a *stochastic* test it can be quite hard to track down.
> add seeds to slim tests; closes #1201

- tests/test_models.py
As triggered by https://github.com/popsim-consortium/stdpopsim/issues/1598#issuecomment-2551983948 I looked into the test warnings due to model specific mutation and recombination rate.
One test warning was not intended, so I fixed that.
I am a bit confused what to do with these ones:
```
> python3 -m pytest tests/test_models.py
========================================================================= test session starts =========================================================================
platform darwin -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/ggorjanc/Storages/GitBox/popsim/stdpopsim/stdpopsim_fork
configfile: setup.cfg
plugins: xdist-3.6.1
4 workers [275 items]   
................................................................................................... …
```
> Squashing unintended test warnings due to model recombination rate

- tests/test_models.py
Following upon https://github.com/popsim-consortium/stdpopsim/pull/1626 I now figured out that it was not mitochondrion that was causing the errors, but the fact that model tests in `DemographicModelTestMixin:test_simulation_runs` are ran without recombination, which rightly issued the unintended warning when a model has it's specific rec rate.
We test these warnings in `TestRecombinationRates:test_recombination_rate_warning` and `TestRecombinationRates:test_recombination_rate_match` so I provide this fix to get rid of the unintended recombination rate test warnings.
> Squash unintended recombination rate test warnings

- stdpopsim/catalog/MusMus/__init__.py
- stdpopsim/catalog/MusMus/dfes.py
@igronau Just getting the pull started for MusMus. Here I've implemented the base DFE for CDS from [here](https://www.biorxiv.org/content/10.1101/2021.06.10.447924v2). Note that there is also a DFE for CNE and UTR type genomic sequence but I wanted to make sure the CDS is parameterized correctly first.
> Getting started with DFE for MusMus

- CHANGELOG.rst
- stdpopsim/cli.py
- stdpopsim/slim_engine.py
- tests/test_slim_engine.py
Hopefully it is this simple!  *Edit: it was not.*
> enable slim on windows

- CHANGELOG.rst
- stdpopsim/qc/CanFam.py
- stdpopsim/qc/__init__.py
This PR addresses https://github.com/popsim-consortium/stdpopsim/issues/1643
I followed the process described in https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#implementing-tests-for-the-review-of-a-demographic-model
My model development is very similar to the initial implementation in https://github.com/popsim-consortium/stdpopsim/pull/1632 since the model is quite straightforward to implement based on the publication - as part of the QC I read the paper and supplements to check the parameters and made extensive comments in the QC code.
Tests related to this QC pass on my end (but others fail or warn). Let's see what GitHub actions throw back at me;)
```
> python3 -m pytest
========================================================================= test session …
```
> QC for EarlyWolfAdmixture_6F14 (CanFam) #1643

- stdpopsim/catalog/AraTha/dfes.py
- stdpopsim/qc/AraTha.py
- tests/test_slim_engine.py
Closes #1344.
I used the gamma distribution parameters from the additive *A. lyrata* model from Table S4 of [Huber et al., 2018](https://doi.org/10.1038/s41467-018-05281-7) to QC the model.
The scale parameter of the distribution is misidentified as `gamma_mean` in the catalog, so I modified the Gamma_H18 DFE in the AraTha catalog to match so that `gamma_mean` is now the product of the shape and scale parameters.
> QC for AraTha DFE

- docs/_ext/speciescatalog.py
this PR adds the `assembly_name` as a field of the `Genome` in the catalog docs. when rendered it looks like this:
this PR will close #1651 when merged
> exposed assembly name in catalog docs

- stdpopsim/genomes.py
Also fixed the code display:
tldr; is that stdpopsim, like msprime/tskit, uses [a,b); while SLiM uses [a,b].
> clarify add_dfe docs (closes #1580)

- docs/_ext/speciescatalog.py
- stdpopsim/catalog/DroMel/dfes.py
- stdpopsim/catalog/HomSap/dfes.py
- stdpopsim/catalog/MusMus/dfes.py
- stdpopsim/catalog/PhoSin/dfes.py
In doing this, I've also edited these descriptions to be readable (they were not). Here's what it looks like.
> include long description in DFE catalog entries

- stdpopsim/catalog/HomSap/dfes.py
Motivation: we'd like to have a DFE containing positive mutations that aren't all at one fixed value of `s`.
[Rodrigues, Kern & Ralph](https://academic.oup.com/genetics/article/226/4/iyae006/7577595) doesn't exactly infer such a DFE, in the sense of using a validated inference procedure, but does explore parameter space and find a best-fitting DFE - so, I think it counts, and since it is simulation-based, we know it produces roughly reasonable simulations. The targets of inference are only the proportions of positive and negative selection; the negative part of the DFE is from [Castellano et al](https://academic.oup.com/genetics/article/226/4/iyae006/7577595), which I also cite here; the positive part is based on "expert knowledge" (i.e., something that seems reasonable).
So, in the …
> add pos & neg DFE from Rodrigues et al (PosNeg_R24 in HomSap)

- docs/_static/custom.css
- docs/_templates/footer.html
- docs/conf.py
this changes the `doc/conf.py` to pull the version and release info automatically from the `setuptools_scm` interface as requested in #680 
will close #680
> get release / version info from setuptools_scm

- .github/workflows/docs.yml
patching docs workflow to checkout the repo with the full tag history so that version/release info can be included in the docs
will close #680 (again)
> added fetch depth 0 to checkout

- stdpopsim/catalog/AnoCar/species.py
- tests/test_AnoCar.py
recombination rate estimate for AnoCar from a linkage map for the common lizard, Zootoca vivipara, from this paper: https://doi.org/10.1093/gbe/evaa161
closes #1365
> lizard recomb rate estimate

- stdpopsim/catalog/DroMel/dfes.py
- stdpopsim/catalog/HomSap/dfes.py
This is as recommended by @klohmueller over in #1469. It's really just Huber et al's Gamma_H17 except a proportion `p` of the changes are beneficial with coefficient `s`; [the paper](https://genome.cshlp.org/content/31/1/110.abstract) shows that `p` and `s` are highly confounded (and `ps` can be estimated better); but these are the MLE values. These values are using divergence to chimp.
Kirk said:
> For a DFE with positive selection in humans—we could use this one from Table S6 of Zhen et al. (2021). This DFE is for nonsynonymous mutations. We inferred 1.55% of nonsynonymous mutations were positively selected in humans with a s of 0.0001124605. The remaining nonsynonymous mutations came from a DFE for negative selection (parameters for this are in Table S3). The shape parameter is 0.19 …
> positive-containing DFE from Zhen et al 2021 (GammaPos_Z21, HomSap and DroMel)

- stdpopsim/qc/HomSap.py
Addresses #1691 
I used the Huber et al. 2017 gamma-distributed DFE with a proportion of nonsynonymous mutations being positively selected. Parameters for the positively-selected mutations were based on the discussion in #1469.
> QC for Zhen 2017 Homsap DFE

- stdpopsim/qc/HomSap.py
Addresses #1507 -- I used the parameters (with discrete dominance coefficients) from supplemental section S6 in [Kyriazis et al. 2023](https://doi.org/10.1086/726736), with a 0.3% of *nonsynonymous* mutations being lethal. 
I used the 2.31:1 nonsynonymous:synonymous ratio described in Huber et al. as per the discussion in #1507.
> generic DFE from kyriazis

- stdpopsim/qc/HomSap.py
- tests/test_dfes.py
addresses #1484
I used table S3 from [Huber et al. 2017](https://doi.org/10.1073/pnas.1619508114) for the parameters and refactored the mu value of the LogNormal distribution to account for DaDi vs. SLiM scaling. I also modified the DFE tests so that they can accept LogNormal distribution arguments (which are strings, not floats).
> LogNormal DFE for humans

- stdpopsim/catalog/DroMel/dfes.py
- stdpopsim/qc/DroMel.py
Addresses #1690 
I used the Huber et al. 2017 gamma-distributed DFE with a proportion of nonsynonymous mutations being positively selected. Parameters for the positively-selected mutations were from Table S6 in the [Zhen et al. paper.](https://genome.cshlp.org/content/31/1/110.abstract)
> DroMel positive DFE

- CHANGELOG.rst
- stdpopsim/catalog/DroMel/dfes.py
- stdpopsim/qc/DroMel.py
- tests/test_dfes.py
Addresses #1697
I used the parameters from tables S1 (LogNormal distribution parameters, positive selection coefficient) and S2 (proportion of NS mutations that are positive). Because the parameters in S1 are scaled by 2Ne, I divided them by 2Ne using the effective population size from Huber et al. 
Since the paper used DaDi to infer their DFEs, I rescaled the mu term so that the expected mean (X = exp(mu + (sigma^2)/2)) of the LogNormal distribution was two times the inferred mean (after scaling by 2Ne).
> dromel lognormal DFE

- tests/test_GorGor.py
**QCing the species addition for GorGor #1517** 
this pertains to issue #1659 as well
I've gone through and everything looks good except for the mutation rates initially drafted by @ChristianHuber 
The mutation rate estimate in the catalog currently is 1.235e-08. Looking at the [citation](https://www.nature.com/articles/s41559-018-0778-x) I see that they sequenced two gorilla trios, one of which had a rate of 1.03e-08 and the other which was at 1.22e-08. Averaging these I came up with a rate of 1.125e-08. 
@ChristianHuber -- do you see different numbers reported?
> QC for GorGor

- docs/parameter_tables/HomSap/PapuansOutOfAfrica_10J19.csv
will close #1707 
as pointed out in that issue, the docs  parameter table for `PapuansOutOfAfrica_10J19` was off by two orders of magnitude for two of the migration params. 
it used to say:
Migration rate (x10^-4): 31.4 European–East Asian migration rate
Migration rate (x10^-4): 57.2 East Asian–Papuan migration rate
but in the code has:
m_EU_AS = 3.14e-5
m_AS_Papuan = 5.72e-5
this PR fixes this params displayed in the documentation to match the code
> param table edit for PapuansOutOfAfrica_10J19

- docs/installation.rst
- setup.cfg
@bhaller reports that running
```
stdpopsim -e slim --slim-script --slim-scaling-factor 10 HomSap -g HapMapII_GRCh38 -c chr22 --left 10000000 --right 20000000 -o foo.ts -d OutOfAfrica_2T12 AFR:1 EUR:2
```
results in
```
Traceback (most recent call last):
File "/Users/bhaller/Library/Python/3.9/bin/stdpopsim", line 8, in <module>
sys.exit(stdpopsim_main())
File "/Users/bhaller/Library/Python/3.9/lib/python/site-packages/stdpopsim/cli.py", line 1157, in stdpopsim_main
run(args)
File "/Users/bhaller/Library/Python/3.9/lib/python/site-packages/stdpopsim/cli.py", line 1148, in run
args.runner(args)
File "/Users/bhaller/Library/Python/3.9/lib/python/site-packages/stdpopsim/cli.py", line 868, in run_simulation
ts = engine.simulate(**kwargs)
File …
```
> bump min python version
